### PR TITLE
Store output of Kafka container commands

### PR DESCRIPTION
**Pull request by kokosing**
Store output of Kafka container commands

### CODE REVIEW

**Comment by bsideup** [comment]
Hi @kokosing,

Could you please explain the motivation first? Thanks!

**Comment by kokosing** [comment]
@bsideup Thanks to this we would have minimal introspection into Kafka and Zookeeper processes. In my custom usage of `KafkaContainer` I pass environment variables that influences the behaviour of these processes. And sometimes they simply do not start and `KafkaContainer` is terminated after a timetout. Having logs captured I am able to determine the failure root cause.

**Comment by bsideup** [comment]
@kokosing in #2078, we changed Kafka to not run a sub-process, but wait for the command to be created.
It makes the default log introspection (getLogs(), also will be printed if the container fails to start) work.

Have you tried 1.12.4?

**Comment by kokosing** [comment]
> Have you tried 1.12.4?

Not yet. Thanks I will give it a shot.

**Pull request closed without merging**
