### PR TITLE
Allow setting the default exposed port.

### PR DESCRIPTION
**Pull request by abersnaze**
I had an issue with the Cassandra image that I wanted to use only listening on 7104.

### CODE REVIEW

**Comment by abersnaze** [comment]
It was not easy to work around because the CQL_PORT and getCluster are static.

**Comment by bsideup** [comment]
@abersnaze they exist to make it easier to access the state.

However, you can use the code from that method without having to modify the module

**Comment by abersnaze** [comment]
if I copy the contents of the method I'll have to maintain it.

**Comment by bsideup** [comment]
@abersnaze the method contains standard Cassandra client configuration and uses the public API of Testcontainers - `getContainerIpAddress` and `getMappedPort`, there isn't anything to maintain :)

**Comment by rnorth** [comment]
@abersnaze do you want to pursue this PR or shall we close?

**Comment by rnorth** [comment]
Closing.

**Pull request closed without merging**
