### PR TITLE
Put all docker compose files into environment before starting

### PR DESCRIPTION
**Pull request by zbstof**
Currently, only first docker-compose entry is put into environment:
```
new DockerComposeContainer(
                new File(Initializer.class.getResource("/docker/docker-compose.yml").toURI()),
                new File(Initializer.class.getResource("/docker/docker-compose-app.yml").toURI()))
              ...
                .withLocalCompose(true)
                .withPull(false);
```
will fail, when started, to the effect that properties from second docker-compose weren't applied

### CODE REVIEW

**Comment by zbstof** [comment]
I can try, I'm not good with grade, though. Which command should I run to
compile and run tests?

**Comment by rnorth** [comment]
Thanks - if you run `./gradlew check` (Linux/MacOS) or `gradlew.bat check` that should work!

The tests take quite a while to run, so I'd recommend just running your own test class in your IDE if you can while developing it.

Thanks again.

**Comment by zbstof** [comment]
I think this test will require `docker-compose` to be present on build service?
Is this the case for Circle-CI?

Also, Intellij fails compilation, and from command-line I cannot run single test for some reason:
```
./gradlew test --tests org.testcontainers.junit.DockerComposeLocalOverrideTest
> Task :couchbase:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':couchbase:test'.
> No tests found for given includes: [org.testcontainers.junit.DockerComposeLocalOverrideTest](--tests filter)
```
`DockerComposeLocalOverrideTest` - this is my test

**Comment by zbstof** [comment]
Ok, with new test, but without the fix:
```
Gradle Test Executor 6 > org.testcontainers.junit.DockerComposeLocalOverrideTest > testEnvVar FAILED
    org.rnorth.ducttape.TimeoutException: Timeout waiting for result with exception
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:51)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilTrue(Unreliables.java:95)
        at org.testcontainers.junit.DockerComposeLocalOverrideTest.testEnvVar(DockerComposeLocalOverrideTest.java:54)

        Caused by:
        java.lang.RuntimeException: Not ready yet
```
With fix test passes

**Comment by rnorth** [comment]
Thanks @zbstof, I'll have a look now!

**Comment by rnorth** [comment]
I'm just going to push a slight change if that's OK; I've combined three similar test classes into one class that has parameterized tests.

This was something that needed to be done before your change, it's just a bit more necessary now.

**Comment by rnorth** [comment]
Thanks for this @zbstof - I've merged into master

**Comment by rnorth** [comment]
Released in [1.8.1](https://github.com/testcontainers/testcontainers-java/releases/tag/1.8.1)! 🎉

Thanks for your contribution @zbstof!

**Pull request merged**
