### PR TITLE
Kotlin example

### PR DESCRIPTION
**Pull request by eaxdev**
Added an example that shows how to use `Testcontainers` along with the `Kotlin` language and `Spring Boot` application. The example uses the `GenericContainer` and Redis

### CODE REVIEW

**Comment by eaxdev** [comment]
Hi, @bsideup .

1. Can I use `Redis` image as an example? Is it not heavy? 
2. Okay, are you suggesting we use [this](https://github.com/testcontainers/testcontainers-java/issues/318#issuecomment-290692749) workaround? 
3. Fixed

**Comment by bsideup** [comment]
@eaxdev 
1) yes, Redis is a good candidate.
2) I would use something like this:
```kotlin
@ClassRule
@JvmField
val redis = object : GenericContainer<Nothing>("redis:3-alpine") {
	init {
		withExposedPorts(6379)
	}
}
```

(this is pretty aligned with the ideas we have about the next generation of our DSL)

**Comment by eaxdev** [comment]
1. I replaced the `Kafka` container with `Redis`
2. I did it, but through an object companion. That's because `@ClassRule` wants a static field

**Comment by eaxdev** [comment]
Hi, could you review the changes? All review comments have been addressed. Or need something else to fix? Thank!

**Comment by bsideup** [comment]
hi @eaxdev,

I just applied a few changes, should be good to merge after the CI reports green status :)

**Comment by bsideup** [comment]
@eaxdev merged. Thanks! 👍

**Pull request merged**
