### PR TITLE
chore: Set permissions for GitHub actions

### PR DESCRIPTION
**Pull request by naveensrinivasan**
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by eddumelendez** [comment]
@naveensrinivasan thanks for the PR! just one question. do we nalso eed the permission content:read [here](https://github.com/testcontainers/testcontainers-java/blob/master/.github/workflows/ci.yml), right?

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan thanks for the PR! just one question. do we also need the permission content:read [here](https://github.com/testcontainers/testcontainers-java/blob/master/.github/workflows/ci.yml), right?

I think so.

**Comment by kiview** [comment]
@naveensrinivasan Would you also like to contribute this change, so we have everything together in this PR? 🙂

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan Would you also like to contribute this change, so we have everything together in this PR? 🙂

Apologies I won’t be able to do it. Thanks

**Review by eddumelendez — APPROVED** [review]

**Comment by eddumelendez** [comment]
thanks for your contribution @naveensrinivasan ! this is now merged in master branch

**Pull request merged**
