### PR TITLE
Add additional constructor to OracleContainer

### PR DESCRIPTION
**Pull request by rwiskerke**
This makes it possible to use an container based on a Dockerfile instead of a published image

### CODE REVIEW

**Comment by rnorth** [comment]
@rwiskerke thanks - this looks like a good idea given the need to 'bring your own' Oracle images.

Thank you for the contribution!

Would you mind adding a changelog entry, then I think we're good to go. Thanks.

**Comment by bsideup** [comment]
@rnorth aren't we agreed to add it ourselves?

**Comment by rwiskerke** [comment]
@rnorth @bsideup Added the change to the changelog, but feel free to edit the entry if you like.

**Comment by kiview** [comment]
@rwiskerke Thanks a lot, I made a slight change to the wording :wink:

**Pull request merged**
