### PR TITLE
Move static config in modules to constructor

### PR DESCRIPTION
**Pull request by MitchJust**
As discussed with @bsideup on slack, static config should be applied in the constructor, not in configure()

### CODE REVIEW

**Comment by rnorth** [comment]
This was released in https://github.com/testcontainers/testcontainers-java/releases/tag/1.14.0 🎉

Thanks for the contribution!

**Comment by bsideup** [comment]
@aguibert already fixed in today's 1.14.1, sorry!

**Comment by aguibert** [comment]
@bsideup did you fix the Oracle container in a different commit that I'm not seeing? I only see the MariaDB and MySQL containers updated in the linked commit here: https://github.com/testcontainers/testcontainers-java/commit/d604f3ec45c9c61574b1728b801b70dba35eaa18

**Comment by bsideup** [comment]
@aguibert yeah, updated my initial answer :(

**Comment by aguibert** [comment]
I think there is also a 2nd (probably less impactful) regression that we may need to look at. I had a `CustomPostgreSQLContainer` that extended the `PostgreSQLContainer` and overrode the `configure()` method. Previously this worked, but now there seems to be an error because `addExposedPort` is being called on the same port twice, which appears to cause an error later on.

Perhaps to fix this one `GenericContainer.exposedPorts` should be converted to an ordered set like `LinkedHashSet` instead of an `ArrayList` to prevent duplicate values from going into the exposed ports?

Here is the full stack trace of the error I'm hitting:
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:320)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:300)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1011)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:83)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:313)
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:488)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:315)
	at org.testcontainers.containers.GenericContainer$$Lambda$144.00000000A163DDD0.call(Unknown Source)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
Caused by: java.lang.RuntimeException: org.testcontainers.shaded.com.fasterxml.jackson.databind.JsonMappingException: Failed to getValue() with method com.github.dockerjava.api.model.ExposedPorts#toPrimitive(0 params): null (through reference chain: com.github.dockerjava.core.command.CreateContainerCmdImpl["ExposedPorts"]->com.github.dockerjava.api.model.ExposedPorts["toPrimitive()"])
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:134)
	at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:33)
	at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:595)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.testcontainers.dockerclient.AuditLoggingDockerClient.lambda$wrappedCommand$14(AuditLoggingDockerClient.java:102)
	at org.testcontainers.dockerclient.AuditLoggingDockerClient$$Lambda$104.00000000A14EF810.invoke(Unknown Source)
	at com.sun.proxy.$Proxy23.exec(Unknown Source)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:397)
Caused by: org.testcontainers.shaded.com.fasterxml.jackson.databind.JsonMappingException: Failed to getValue() with method com.github.dockerjava.api.model.ExposedPorts#toPrimitive(0 params): null (through reference chain: com.github.dockerjava.core.command.CreateContainerCmdImpl["ExposedPorts"]->com.github.dockerjava.api.model.ExposedPorts["toPrimitive()"])
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:356)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ser.std.JsonValueSerializer.serialize(JsonValueSerializer.java:183)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:4110)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3437)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:126)
Caused by: java.lang.IllegalArgumentException: Failed to getValue() with method com.github.dockerjava.api.model.ExposedPorts#toPrimitive(0 params): null
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.introspect.AnnotatedMethod.getValue(AnnotatedMethod.java:186)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ser.std.JsonValueSerializer.serialize(JsonValueSerializer.java:166)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.introspect.AnnotatedMethod.getValue(AnnotatedMethod.java:183)
Caused by: java.lang.IllegalStateException: Duplicate key 5432/tcp (attempted merging values java.lang.Object@f203e3d8 and java.lang.Object@54902a24)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.util.stream.Collectors$$Lambda$112.00000000A1332450.accept(Unknown Source)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.github.dockerjava.api.model.ExposedPorts.toPrimitive(ExposedPorts.java:38)
```

**Comment by bsideup** [comment]
@aguibert fixed the Oracle one in https://github.com/testcontainers/testcontainers-java/pull/2612

**Comment by bsideup** [comment]
And the ports: https://github.com/testcontainers/testcontainers-java/pull/2613

**Pull request merged**
