### PR TITLE
Support multiple init scripts in JdbcDatabaseContainer

### LINKED ISSUE #2232: Improve usability of SQL init scripts with multiple file support
# Context

Issue originally raised [on stackoverflow](https://stackoverflow.com/questions/59024184/spring-boot-with-testcontainers-how-to-prevent-db-initialization-on-context-re/59207762#59207762) as a question.

It would be useful to be able to initialize a database with multiple startup scripts. In most projects that I've worked on, there are multiple onboarding scripts (database, schema, data, test-data etc). As such, when provisioning a new database using testcontainers for an integration test, it'd be helpful to be able to execute all of these scripts on startup without needing to merge them into a single script.

# Suggestion

An additional API in `JdbcDatabaseContainer`

```
/**
  * Execute each script in the order of which they're provided
  */
public SELF withInitScript(String... initScriptPaths) {
    // ...
}
```

An additional consideration for this API might be the result of [2127](https://github.com/testcontainers/testcontainers-java/issues/2127)

### PR DESCRIPTION
**Pull request by savinov**
Inspired by PRs: #2578 and #1997
Closes #2232

### CODE REVIEW

**Comment by mrsofiane** [comment]
This feature is essential, the PR looks good, I hope it will be accepted as soon as possible, good work.

**Comment by ujjaldey** [comment]
This is a must-have feature. Could anyone please approve and merge this PR?

**Comment by sdavids** [comment]
Using `private Map<String, String> initScriptPaths = new LinkedHashMap<>();` would support my use case #8634.

**Comment by eddumelendez** [comment]
Thanks for your contribution, @savinov !

**Comment by Asya-Vorobyova** [comment]
Looks like this change is breaking for the case when initScriptPath isn't provided. Then initScriptPaths is initialized with one null element, and then application failed when trying to get the resource in ScriptUtils.runInitScript() method.

**Comment by mikymigs** [comment]
> Looks like this change is breaking for the case when initScriptPath isn't provided. Then initScriptPaths is initialized with one null element, and then application failed when trying to get the resource in ScriptUtils.runInitScript() method.

Same issue

**Comment by Asya-Vorobyova** [comment]
@savinov could somebody fix it, please? Thnx in advance :)

**Pull request merged**
