### PR TITLE
Fix for setting ryuk.container.timeout causes a ClassCastException

### PR DESCRIPTION
**Pull request by jamieswogger**

### CODE REVIEW

**Comment by bsideup** [comment]
Hi @jamieswogger! 
Oh wow, nice catch! Sorry for that 🤦‍♂️ 

Could you please mention your change in CHANGELOG.md? Thanks!

**Comment by jamieswogger** [comment]
No worries, @bsideup, and thanks for the quick response!

Added a comment to the CHANGELOG.md

**Comment by bsideup** [comment]
@jamieswogger merged, thanks a lot!

**Comment by jamieswogger** [comment]
Sound good - thanks, @bsideup!

**Comment by jamieswogger** [comment]
Hey @bsideup - do you think this will get released in a bugfix version this week? Thanks!

**Comment by bsideup** [comment]
Hi @jamieswogger,

Yes, sure, didn't make it to release on the weekends, but we're doing our best to release it ASAP! 
There are a couple of other findings we want to fix, but expect it to be released really soon.

And one more time - thanks for your contribution 👍

**Pull request merged**
