### PR TITLE
shade aopalliance to reduce the chance for conflicts

### PR DESCRIPTION
**Pull request by dbyron0**
Before:
```
$ jar tvf testcontainers-1.2.0.jar | grep org/aopalliance
     0 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/
     0 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/aop/
     0 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/instrument/
     0 Sun Mar 12 21:13:28 PDT 2017 org/aopalliance/intercept/
     0 Sun Mar 12 21:13:28 PDT 2017 org/aopalliance/reflect/
   113 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/aop/Advice.class
  1789 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/aop/AspectException.class
   463 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/instrument/Instrumentation.class
   835 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/instrument/InstrumentationError.class
  1537 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/instrument/Instrumentor.class
   783 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/instrument/UndoNotSupportedException.class
   336 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/intercept/ConstructorInterceptor.class
   254 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/intercept/ConstructorInvocation.class
   375 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/intercept/FieldAccess.class
   332 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/intercept/FieldInterceptor.class
   163 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/intercept/Interceptor.class
   217 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/intercept/Invocation.class
   297 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/intercept/Joinpoint.class
   318 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/intercept/MethodInterceptor.class
   234 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/intercept/MethodInvocation.class
   562 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/reflect/Class.class
   172 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/reflect/ClassLocator.class
   524 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/reflect/Code.class
   166 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/reflect/CodeLocator.class
   305 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/reflect/Field.class
   119 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/reflect/Locator.class
   384 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/reflect/Member.class
   180 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/reflect/Metadata.class
   326 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/reflect/Method.class
   443 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/reflect/ProgramUnit.class
   166 Sun Mar 12 21:13:22 PDT 2017 org/aopalliance/reflect/UnitLocator.class
```

After:
```
$ jar tvf core/target/testcontainers-1.2.1-SNAPSHOT.jar | grep org/aopalliance
     0 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/
     0 Wed Mar 15 17:04:02 PDT 2017 org/testcontainers/shaded/org/aopalliance/aop/
     0 Wed Mar 15 17:04:02 PDT 2017 org/testcontainers/shaded/org/aopalliance/instrument/
     0 Wed Mar 15 17:04:02 PDT 2017 org/testcontainers/shaded/org/aopalliance/intercept/
     0 Wed Mar 15 17:04:02 PDT 2017 org/testcontainers/shaded/org/aopalliance/reflect/
   139 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/aop/Advice.class
  1841 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/aop/AspectException.class
   515 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/instrument/Instrumentation.class
   939 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/instrument/InstrumentationError.class
  2135 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/instrument/Instrumentor.class
   887 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/instrument/UndoNotSupportedException.class
   414 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/intercept/ConstructorInterceptor.class
   306 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/intercept/ConstructorInvocation.class
   427 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/intercept/FieldAccess.class
   410 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/intercept/FieldInterceptor.class
   215 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/intercept/Interceptor.class
   269 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/intercept/Invocation.class
   323 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/intercept/Joinpoint.class
   396 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/intercept/MethodInterceptor.class
   286 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/intercept/MethodInvocation.class
   744 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/reflect/Class.class
   224 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/reflect/ClassLocator.class
   732 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/reflect/Code.class
   218 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/reflect/CodeLocator.class
   409 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/reflect/Field.class
   145 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/reflect/Locator.class
   462 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/reflect/Member.class
   206 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/reflect/Metadata.class
   456 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/reflect/Method.class
   573 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/reflect/ProgramUnit.class
   218 Wed Mar 15 17:03:54 PDT 2017 org/testcontainers/shaded/org/aopalliance/reflect/UnitLocator.class
```

### CODE REVIEW

**Comment by bsideup** [comment]
I'm wondering where does it come from. Don't you mind if I'll postpone a merge a little bit and investigate the root cause?

Thanks anyway!

**Comment by dbyron0** [comment]
Pretty sure it comes from https://github.com/hk2-project/hk2/blob/5ca36681f1d6dd4f3b245056a211e9371424006e/external/aopalliance/pom.xml, via this snippet from mvn dependency:tree:
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ testcontainers ---
[INFO] org.testcontainers:testcontainers:jar:1.2.1-SNAPSHOT
[INFO] +- com.github.docker-java:docker-java:jar:3.0.7:compile
[INFO] |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.6.4:compile
[INFO] |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.6.4:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.6.4:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.4:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.6.4:compile
[INFO] |  +- org.glassfish.jersey.connectors:jersey-apache-connector:jar:2.23.1:compile
[INFO] |  |  +- org.glassfish.jersey.core:jersey-common:jar:2.23.1:compile
[INFO] |  |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |  |  +- org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.23.1:compile
[INFO] |  |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO] |  |  \- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.5:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-client:jar:2.23.1:compile
[INFO] |  |  +- org.glassfish.hk2:hk2-api:jar:2.4.0-b34:compile
[INFO] |  |  |  +- org.glassfish.hk2:hk2-utils:jar:2.4.0-b34:compile
[INFO] |  |  |  \- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.4.0-b34:compile
```

**Comment by rnorth** [comment]
@bsideup any objection to merging this now?

**Comment by bsideup** [comment]
@rnorth not really, we can make a follow-up task :)

**Comment by rnorth** [comment]
Cool, 👍

**Comment by dbyron0** [comment]
Thanks much!

**Pull request merged**
