### PR TITLE
Support using MariaDB JDBC URL to set database name, user and password

### PR DESCRIPTION
**Pull request by guss77**
Implement feature compatibility with MySQL container requested in issue #949

### CODE REVIEW

**Comment by kiview** [comment]
Hi @guss77, thanks for the PR.
Can you please add the corresponding tests to https://github.com/testcontainers/testcontainers-java/blob/1d0140aba9956f6e53cbfdcb50c4f2537a9fe64d/modules/jdbc-test/src/test/java/org/testcontainers/jdbc/JDBCDriverTest.java#L52?

**Comment by guss77** [comment]
Something like this?

**Comment by kiview** [comment]
Yes, thanks.
Do you know if these check will fail, if you revert the changes you did to `MariaDBContainer`?

**Comment by guss77** [comment]
Interestingly enough, without the MariaDbContainer support for user and password, the only test that fails is `jdbc:tc:mariadb://hostname/databasename?user=someuser&TC_INITSCRIPT=somepath/init_mariadb.sql` on an assert at `JDBCDriverTest.java:140` which tests that the "current user" is `someuser` (hardcoded?).

This actually makes sense to me - this PR is about obeying the configuration from the URL, so without it the container still starts, but uses the "`test`" username so the only way to check that is to check if the current logged in used matches what we expect from the URL.

The only question is why the other tests with a user in the URL didn't fail, and I think I understand why.

**Comment by guss77** [comment]
With the last change, all MariaDB tests with a custom user name fail without the PR changes.

**Comment by kiview** [comment]
Thanks, LGTM to me now.
But for JDBC PRs, it's always good if @rnorth gives it an additional look :slightly_smiling_face:

**Comment by rnorth** [comment]
LGTM, thank you @guss77!

**Pull request merged**
