### PR TITLE
Add docker compose support for --build and --rmi options

### PR DESCRIPTION
**Pull request by lightoze**

### CODE REVIEW

**Comment by rnorth** [comment]
Ah, thank you @lightoze, this seems like a sensible addition!

Could you possibly create a test in case we accidentally break this in the future?
If the `rmi` feature is too hard to test then maybe skip that, but I imagine it should be possible to create a test for the `build` flag.

**Comment by rnorth** [comment]
I'll apply the help wanted label so that anybody else interested can pick this up, in case @lightoze is too busy.

I think my [comment](https://github.com/testcontainers/testcontainers-java/pull/924#issuecomment-433651167) gives the gist of what we'd be after.

@sonerd, would you be interested in picking this up?

**Comment by sonerd** [comment]
> I'll apply the help wanted label so that anybody else interested can pick this up, in case @lightoze is too busy.
> 
> I think my [comment](https://github.com/testcontainers/testcontainers-java/pull/924#issuecomment-433651167) gives the gist of what we'd be after.
> 
> @sonerd, would you be interested in picking this up?

Sure I can give it a try. Should I fork from latest master and cherry-pick the changes made by @lightoze ?

**Comment by lightoze** [comment]
@sonerd I would be glad for you doing that. I'm still not getting back to the project where testcontainers is in use.

**Comment by sonerd** [comment]
I have created a new PR: https://github.com/testcontainers/testcontainers-java/pull/1336

**Comment by rnorth** [comment]
Closing in favour of #1336

**Pull request closed without merging**
