### PR TITLE
Container image as future

### PR DESCRIPTION
**Pull request by rnorth**
Additional merge refactoring and updates for #106

### CODE REVIEW

**Comment by bsideup** [comment]
@rnorth if it's possible, please, **do not** merge it yet - I'm currently working on Dockerfile already and this changes will be supercided (see Gitter)

**Comment by rnorth** [comment]
Ah, damn, sorry I missed that message. I just saw your comment on #106 - do you want to take the lead on #117 and this branch? I'll just let you get on with it if there's a lot that's going to change!

**Comment by rnorth** [comment]
@bsideup - just merged your dockerfile support PR! I assume this one (Future for image name) can be closed?

**Comment by bsideup** [comment]
@rnorth woooo :tada: sure, everything from this PR was included in Dockerfile PR. Thanks!

**Pull request closed without merging**
