### PR TITLE
include note about spring boot

### PR DESCRIPTION
**Pull request by BloodChiefStromberg**
Hey -- I ran into the issue described here (https://github.com/testcontainers/testcontainers-java/issues/256#issuecomment-506963471) and it took me a while to find the solution (mentioned in the comment directly below the one I linked). Adding this to the docs might help, although I did notice the rest of the docs seem framework agnostic.

### CODE REVIEW

**Comment by BloodChiefStromberg** [comment]
Sure, I get the concern. If you find a better place, I'm happy to move it. I do think this belongs in the docs somewhere though -- I think breaking the agnostic tenor of the docs is better than letting other people struggle with a solved problem 🤷‍♂ hopefully we can do both!

**Comment by bsideup** [comment]
@rnorth perhaps we can change it to "for examples of how to pass these dynamic values to various frameworks, consider checking the `examples/` folder" ?

**Comment by rnorth** [comment]
Should not be stale - let's do as suggested

**Comment by kiview** [comment]
We close the PR as-is but intend to follow the suggestion to add references to the existing `/examples` to the documentation. Sorry for leaving this hanging forever @BloodChiefStromberg, but we appreciate you opening up this discussion.

**Pull request closed without merging**
