### PR TITLE
Added "docker exec" type functionality to GenericContainer. #103

### PR DESCRIPTION
**Pull request by ostacey**
Cleaned up version; tests should pass now.

### CODE REVIEW

**Comment by rnorth** [comment]
Thanks, this looks good to me. I'll have a play with this and aim to merge this evening.

**Comment by rnorth** [comment]
Ah, running this I noticed that the container output was appearing on System.err as well as being buffered. It looks like the docker-java lib's `ExecStartResultCallback` has a side effect of println'ing everything to System.err:
```
 @Override
    public void onNext(Frame frame) {
        if (frame != null) {
            try {
                switch (frame.getStreamType()) {
                case STDOUT:
                case RAW:
                    if (stdout != null) {
                        System.err.println(new String(frame.getPayload()));
                        stdout.write(frame.getPayload());
                        stdout.flush();
```

I'm not sure if this is a bug or desired behaviour in docker-java but I think it's a bit undesirable here. Do you think you could replace with a callback that just does the desired buffering? Given that the out of the box callback doesn't seem to be an exact match, I suspect that there's a nice DRY option through extraction of [this](https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/GenericContainer.java#L675) into a proper class and use of [ToStringConsumer](https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/output/ToStringConsumer.java)..!

**Comment by rnorth** [comment]
I'll defer this to 1.0.4 if you don't mind, though I hope to release it quite quickly after 1.0.3.

**Comment by rnorth** [comment]
I noticed that the Travis build job failed on pulling a container image, so I've retriggered that build.

**Comment by ostacey** [comment]
Also included here, because it builds on the refactoring I did around outputting callbacks: when a container fails to start up, (optionally) capture its output in the logs.

Adding a unit test for this required that I bring in Mockito.

**Comment by ostacey** [comment]
Looks like I'm seeing the same issue here as I was with #115. I'll back this branch up and leave the log capture stuff until later.

**Comment by rnorth** [comment]
Looks good to me - thank you. Merged!

**Pull request merged**
