### PR TITLE
Add support for ActiveMQ and Artemis

### PR DESCRIPTION
**Pull request by eddumelendez**
The following implementations have been implemented:
* `ActiveMQContainer` supports [ActiveMQ](https://hub.docker.com/r/apache/activemq-classic)
* `ArtemisContainer` supports [Artemis](https://hub.docker.com/r/apache/activemq-artemis)

### CODE REVIEW

**Comment by eddumelendez** [comment]
To support ActiveMQ credentials, see https://github.com/apache/activemq/pull/1050

**Comment by jbonofre** [comment]
I'm adding the env variables required in ActiveMQ, updating apache/activemq#1050

**Comment by jbonofre** [comment]
I'm updating the ActiveMQ docker images to support the env variables.

**Comment by eddumelendez** [comment]
I've raised [AMQ-9412](https://issues.apache.org/jira/browse/AMQ-9412) due to container doesn't start when credentials are set. It will be also nice to provide images for platform `linux/amd64`

**Pull request merged**
