### PR TITLE
Add NATS support module

### PR DESCRIPTION
**Pull request by kkocel**
### Default docker image

- [X] Should be a Docker Hub official image, or published by a reputable source (ideally the company or organisation that officially supports the technology)
- [X] Should have a verifiable open source Dockerfile and a way to view the history of changes
- [X] MUST show general good practices regarding container image tagging - e.g. we do not use latest tags, and we do not use tags that may be mutated in the future
- [X] MUST be legal for Testcontainers developers and Testcontainers users to pull and use. Mechanisms exist to allow EULA acceptance to be signalled, but images that can be used without a licence are greatly preferred.

### Module dependencies

- [X] The module should use as few dependencies as possible,
- [X] Regarding libraries, either:
  - they should be compileOnly if they are likely to already be on the classpath for users' tests (e.g. client libraries or drivers)
  - they can be implementation (and thus transitive dependencies) if they are very unlikely to conflict with users' dependencies.
- [X] If client libraries are used to test or use the module, these MUST be legal for Testcontainers developers and Testcontainers users to download and use.

### API (e.g. MyModuleContainer class)

- [X] Favour doing the right thing, and least surprising thing, by default
- [X] Ensure that method and parameter names are easy to understand. Many users will ignore documentation, so IDE-based substitutes (autocompletion and Javadocs) should be intuitive.
- [X] The module's public API should only handle standard JDK data types and MUST not expose data types that come from compileOnly dependencies. This is to reduce the risk of compatibility problems with future versions of third party libraries.

### Documentation

- [X] Every module MUST have a dedicated documentation page containing:
- [X] A high level overview
- [X] A usage example
- [X] If appropriate, basic API documentation or further usage guidelines
- [X] Dependency information
- [X] Acknowledgements, if appropriate
- [X] Consider that many users will not read the documentation pages - even if the first person to add it to a project does, people reading/updating the code in the future may not. Try and avoid the need for critical knowledge that is only present in documentation.

### CODE REVIEW

**Comment by kkocel** [comment]
The motivation for this PR is custom wait strategy thay needs to be added in order to make NATS usable (similar issue: https://github.com/testcontainers/testcontainers-java/issues/1733 )

**Comment by bsideup** [comment]
Hi @kkocel,

This does not seem to be answering "yes" to the following question:
https://www.testcontainers.org/contributing/#does-it-need-to-be-a-module

WDYT?

**Comment by kkocel** [comment]
@bsideup from my perspective value added is that this PR adds explicitly a wait strategy that otherwise will be omitted and make nats containers unusable

**Comment by kkocel** [comment]
Replying to keep this alive.

**Comment by LucienBrule** [comment]
Circling back, I think you guys came up with a wonderful solution. A lightweight documentation page/ cook book that mentions NATS and other tech with the use of GenericContainer would work just fine for me at least. I ended up trying GenericContainer and it worked with no issue. I suppose there was some initial confusion

**Comment by kiview** [comment]
Great to hear this @LucienBrule. We will go ahead with this approach very soon. Technically, everything is already in place for this, we just need to add the structure to the docs.

**Comment by kkocel** [comment]
@kiview Let me know when this will be ready - I will reorganize this PR to fit into new structure.

**Comment by eddumelendez** [comment]
@kkocel thanks for the PR, we would like to introduce a NATS sample, similar to #5860.

**Pull request closed without merging**
