### PR TITLE
Check Docker version according to checksEnabled flag

### PR DESCRIPTION
**Pull request by aivinog1**
#1220

### CODE REVIEW

**Comment by kiview** [comment]
Thanks, for the PR.
I think, the change is actually a bit big, considering what we want to achieve.

IMO it's enough to move
https://github.com/testcontainers/testcontainers-java/blob/8acee4d804c125beb3774f509744f31b58ad7fc8/core/src/main/java/org/testcontainers/DockerClientFactory.java#L129
to line 132, inside the if body.

**Comment by aivinog1** [comment]
@kiview Thank you for review. I think you are fair enough. But, may be we need some refactoring to move checks in another class. That will really help us if checks start to grow.

What do you think about it? If you agree I (or maybe you) can create task to do this refactoring.

**Comment by kiview** [comment]
@aivinog1 Having a dedicated environment checking class seems to make sense. I would move all checks there in this case.

However, for now this fix is good to go :slightly_smiling_face:

**Comment by kiview** [comment]
Merged, thanks a lot for your first contribution!

**Comment by rnorth** [comment]
Released in https://github.com/testcontainers/testcontainers-java/releases/tag/1.10.7!

**Pull request merged**
