### PR TITLE
Docs: Use `testImplementation` instead of deprecated `testCompile`

### PR DESCRIPTION
**Pull request by slovdahl**

### CODE REVIEW

**Comment by slovdahl** [comment]
Oops, I managed to miss #3683 before submitting this. Feel free to dismiss this one if you think that's the right approach.

**Comment by kiview** [comment]
Thanks for submitting the PR. This looks much more thorough than #3683.
@bsideup should we close the other PR in favor of this one?

**Review by kiview — APPROVED** [review]

**Comment by rnorth** [comment]
Merging from master to fix build.

**Comment by rnorth** [comment]
Merged. Thanks @slovdahl!

**Pull request merged**
