### PR TITLE
Adding ongdb module for ONgDB (Open Native Graph DB) project

### PR DESCRIPTION
**Pull request by bradnussbaum**
Hi,

I would like to open a request to add a module for ONgDB. ONgDB is a fully open source fork of Neo4j Enterprise which closed source by Neo4j, Inc. as of 3.5. ONgDB is maintained by the [Graph Foundation](https://graphfoundation.org), a non-profit, 501(c)(3) with a mission to make graph technology available for public good.

In order to provide compatibility to the our open source ecosystem, it's important to have a Testcontainers project to support projects like [APOC](https://github.com/graphfoundation/ongdb-apoc/blob/3.6/build.gradle#L189) which relies on the current `Neo4jContainer` and will need to switch to the `OngdbContainer` to allow users to avoid the now proprietary licensing issues of Neo4j Enterprise.

Please consider reviewing this modules addition. I tried to follow the guidelines to the best of my ability in preparing this. I would be happy to make any changes as necessary.

Thanks,
Brad

### CODE REVIEW

**Comment by bradnussbaum** [comment]
Hi,

Did I miss any steps required to have this submission considered for acceptance? I would be happy to make any corrections as needed.

Thanks,
Brad

**Comment by rnorth** [comment]
Sorry - we just have quite a backlog of PRs so haven't really had time to look at this yet. Apologies, we should have responded before letting this get stale.

**Comment by bradnussbaum** [comment]
Please let me know what is needed. Still waiting for first review feedback.

**Comment by kiview** [comment]
Hey @bradnussbaum, thanks for the PR and sorry for keeping this hanging for such a long time.

We currently don't have the capacity to add this module in addition to the existing Neo4j module and I am not sure why the `ONgDB` is not drop-in compatible with the existing `Neo4jContainer`, but we would like to encourage you to publish this module as your own 3rd party module in your own repository, for example under the Graph Foundation, if you see the need for  it.

**Pull request closed without merging**
