### PR TITLE
workaround listNetwork's filter until it's fixed in docker-java

### PR DESCRIPTION
**Pull request by bsideup**
see https://github.com/docker-java/docker-java/issues/857

### CODE REVIEW

**Comment by rnorth** [comment]
Hmm, looks like this is fixed in docker-java [3.0.12](https://github.com/docker-java/docker-java/milestone/22), which seems to be ready for release.

I'm inclined to merge this anyway because this is an annoying issue; we can reverse in 1.4.1 if we upgrade to the latest docker-java.

**Comment by bsideup** [comment]
@rnorth I wasn't sure if it anyhow in users' interest :)

**Comment by rnorth** [comment]
True 😆 
But still might be sensible just in case - e.g. if others have been annoyed by the issue, it would be useful for them to know that it's worth upgrading.

**Comment by bsideup** [comment]
@rnorth fair point. Added :)

**Comment by rnorth** [comment]
LGTM - will merge once the build passes!

**Pull request merged**
