### PR TITLE
#1256 Added fsync=off option by default for postgresql

### PR DESCRIPTION
**Pull request by mumukiller**

### CODE REVIEW

**Comment by mumukiller** [comment]
Any ideas what's with continuous-integration/travis-ci/pr check? As far as i understand build was finished successfully.

**Comment by rnorth** [comment]
There was an unrelated issue with one of the Travis build steps causing a timeout.

I've temporarily disabled Travis CI for another reason anyway, and will update this branch to trigger a new build just using CircleCI.

**Comment by mumukiller** [comment]
Yay! All checks have passed. Thanks for help!

**Comment by rnorth** [comment]
Thanks for the contribution @mumukiller!

**Comment by rnorth** [comment]
Releasing this in [1.11.0](https://github.com/testcontainers/testcontainers-java/releases/tag/1.11.0) 🎉

**Pull request merged**
