### PR TITLE
Add acceptLicense method to MSSQLServerContainer

### PR DESCRIPTION
**Pull request by KyleAure**
Fixes: #2050

Adds accept license method to the MSSQLServerContainer class while still allowing users to accept the license via a resource file.  Updated customizable test class to use the new method, while the simple test class uses the resource file.  Also updated documentation.

### CODE REVIEW

**Comment by KyleAure** [comment]
For issue #2050

**Comment by KyleAure** [comment]
Resolved merge conflicts

**Comment by KyleAure** [comment]
@rnorth thank you so much!  It looks like I don't have authorization to merge.
Is that something you will need to do?

**Comment by rnorth** [comment]
@KyleAure yep - will do now 😄

**Pull request merged**
