### PR TITLE
add "Who is using TestContainers?" to the docs

### PR DESCRIPTION
**Pull request by bsideup**
Approvals:

- [x] ZeroTurnaround @bsideup
- [x] Apache Gora @lewismc
- [x] Apache James @aduprat
- [x] Zipkin @adriancole
- [x] StreamSets @madhukard

### CODE REVIEW

**Comment by adriancole** [comment]
sgtm

**Comment by aduprat** [comment]
:+1:

**Comment by lewismc** [comment]
Nice

**Comment by lewismc** [comment]
👍

**Comment by rnorth** [comment]
Thanks for collating this. We may have a few more to add later, but let's merge now.

**Pull request merged**
