### PR TITLE
Make junit dependency test scope

### PR DESCRIPTION
**Pull request by ali-nutmeg**
The junit dependency was in compile scope and should be in test scope.

### CODE REVIEW

**Comment by ali-nutmeg** [comment]
oops. I think I understand it now.

**Comment by astubbs** [comment]
Can you elaborate as to why it's marked as a compile dep? 
This is causing me some problems. I use jupiter (junit 5).

**Comment by bsideup** [comment]
It was added... with the very first commit :D 

Every type in Testcontainers extends from JUnit 4 types because, back then when Testcontainers was created, JUnit 5 did not exist, and integrating with JUnit 4 made it very easy to adopt the library for many. 

Testcontainers 2.0 will be refactored to remove the dependency on JUnit 4:
https://github.com/testcontainers/testcontainers-java/issues/970

**Comment by astubbs** [comment]
I see :/ I suspect this combination may be causing my surefire to crash..

**Comment by bsideup** [comment]
Never caused a problem to other surefire users, so I would suggest double checking your config

**Comment by astubbs** [comment]
Ah, nope. Sorry - it was this project I'm using for Guice Jupiter adapter: https://github.com/JeffreyFalgout/junit5-extensions/issues/7

**Pull request closed without merging**
