### PR TITLE
Ignore dependencies in specific modules

### PR DESCRIPTION
**Pull request by eddumelendez**
Some dependencies require Java 11, 17 or have a breaking change such
as r2dbc.

### CODE REVIEW

**Comment by kiview** [comment]
Let's also add slf4j here 👍

**Comment by eddumelendez** [comment]
> Let's also add slf4j here 👍

done ✅

**Review by kiview — APPROVED** [review]

**Review by kiview — CHANGES_REQUESTED** [review]
https://github.com/testcontainers/testcontainers-java/pull/5946/checks?check_run_id=8701959280

Broke the yaml:
```
The property '#/updates/0/ignore/0' contains additional properties ["update-type"] outside of the schema when none are allowed
```

**Comment by eddumelendez** [comment]
@kiview dependabot.yml syntax fixed

**Pull request merged**
