### PR TITLE
Generate "exclusions" in POM

### PR DESCRIPTION
**Pull request by bsideup**

### CODE REVIEW

**Comment by bsideup** [comment]
Fixes #753

**Comment by bsideup** [comment]
Fixes #652

**Comment by dbyron0** [comment]
Works for me.  Thanks much.

**Comment by dbyron0** [comment]
The pom that `$ ./gradlew testcontainers:publishToMavenLocal` makes: `~/.m2/repository/org/testcontainers/testcontainers/unspecified/testcontainers-unspecified.pom` has:
```
    <dependency>
      <groupId>net.java.dev.jna</groupId>
      <artifactId>jna-platform</artifactId>
      <version>4.5.1</version>
      <scope>compile</scope>
    </dependency>
```
and no mention of net.java.dev.jna:jna.  In the project where I'm using this, I end up with:
```
|    +--- org.rnorth.visible-assertions:visible-assertions:2.1.0
|    |    \--- net.java.dev.jna:jna:4.5.0 -> 4.2.2
```
and
```
|    \--- net.java.dev.jna:jna-platform:4.5.1
|         \--- net.java.dev.jna:jna:4.5.1 -> 4.2.2
```

where the 4.2.2 comes from https://github.com/spring-projects/spring-boot/blob/v1.5.2.RELEASE/spring-boot-dependencies/pom.xml.

Can you convince maven to use 4.5.1 automatically?  Or do you need a version of visible-assertions that uses 4.5.1 explicitly?

**Comment by arnzel** [comment]
Hi @dbyron0 , thanks for the answer. Do you know how i can try to force maven to use this version automatically ?  Yes the second option would also solve this problem temporarily

**Comment by dbyron0** [comment]
Sorry, can't help you there.

**Comment by rnorth** [comment]
Have you tried adding `net.java.dev.jna:jna:4.5.1` as a direct dependency of your project (temporarily). If I remember correctly that is one way to control the version, or use `dependencyManagement`.

I'll happily merge rnorth/visible-assertions#9 for the medium term...

**Comment by arnzel** [comment]
Hi @rnorth  ,what i tried was this 

<dependency>
            <groupId>myCompany.common.testcontainers</groupId>
            <artifactId>myCompany-testcontainers</artifactId>
            <version>0.5.15</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>net.java.dev.jna</groupId>
                    <artifactId>jna-platform</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.rnorth.visible-assertions</groupId>
                    <artifactId>visible-assertions</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
            <version>4.5.1</version>
        </dependency>
        <dependency>
            <groupId>org.rnorth.visible-assertions</groupId>
            <artifactId>visible-assertions</artifactId>
            <version>2.1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>net.java.dev.jna</groupId>
                    <artifactId>jna-platform</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

where `myCompany.common.testcontainers` has a dependency to

```
    <groupId>org.testcontainers</groupId>
    <artifactId>testcontainers</artifactId>
```

But this does not work

**Comment by arnzel** [comment]
This doesworks for me now. @rnorth  thanks forthe tip with DependencyManagement

<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.java.dev.jna</groupId>
                <artifactId>jna</artifactId>
                <version>4.5.1</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

**Pull request merged**
