### PR TITLE
Add ability to specify docker image in KafkaContainer.

### PR DESCRIPTION
**Pull request by irasikhin**
This code allows to use private docker registry for testing purposes.

### CODE REVIEW

**Comment by bsideup** [comment]
Hi @irasikhin,

What do you think if instead we move `confluentinc/cp-kafka` to `TestcontainersConfiguration`, so that it can be configred with properties?

I really don't want to expose a public "any image" constructor because our KafkaContainer implementation expects image to be Confluent-like and that will be confusing if somebody will try to use some other image.

But I get the point about private registries, and because of them we moved our list of images we use to the `TestcontainersConfiguration` class

**Comment by irasikhin** [comment]
ok, done

**Comment by bsideup** [comment]
@irasikhin I would still keep the ability to specify a version :)

**Comment by bsideup** [comment]
@irasikhin perfect, thank you!

**Comment by irasikhin** [comment]
@bsideup thank you too =)

**Pull request merged**
