### PR TITLE
CreateContainerCmd Link was outdated.

### PR DESCRIPTION
**Pull request by KraTos5589**
Replaced working link

### CODE REVIEW

**Comment by bsideup** [comment]
@KraTos5589 nice! Could you please use versioned link, to avoid a breakage in future? :)

**Comment by KraTos5589** [comment]
@bsideup Done

**Comment by bsideup** [comment]
@KraTos5589 3.0.0 is a bit old, please update to the latest release (3.2.1)

**Comment by KraTos5589** [comment]
@bsideup Updated to 3.2.1

**Comment by KraTos5589** [comment]
Yeah first github PR merged.

**Comment by bsideup** [comment]
@KraTos5589 thank you and congratulations! 🎉
we will try to find time to look at your another (Cassandra) PR soon! 👍

**Comment by KraTos5589** [comment]
Thabks @bsideup , I thought you forgot about that.

**Comment by bsideup** [comment]
@KraTos5589 we never forget about PR, it is just a lack of time :) Sorry for that!

**Pull request merged**
