### PR TITLE
Bumped up default version of Confluent Platform to the current 5.2.1 (Kafka container)

### PR DESCRIPTION
**Pull request by wlsc**
* Bumped up default version of Confluent Platform to the current **5.2.1** (Kafka container)

### CODE REVIEW

**Comment by rnorth** [comment]
As it's a major version bump, are there any changes that could be considered breaking for our users?

**Comment by wlsc** [comment]
@rnorth according to the existing `KafkaContainerTest.java`, there should be no changes that would directly affect existing users. Test has been executed and green.

**Comment by bsideup** [comment]
I reverted the ZK change to verify that the change is backward compatible with external ZK

**Comment by bsideup** [comment]
@wlsc merged, thanks! 👍

**Pull request merged**
