### PR TITLE
Add DgraphContainer module

### PR DESCRIPTION
**Pull request by EnricoMi**
This adds a container module for Dgraph graph database cluster (dgraph.io).

### CODE REVIEW

**Comment by reneleonhardt** [comment]
Can you add `docs/modules/dgraph.md` similar to [mailhog.md](https://github.com/testcontainers/testcontainers-java/blob/dc5ae4b8489efa3a8f8aa46431a598fe46387853/docs/modules/mailhog.md)?

**Comment by EnricoMi** [comment]
@bsideup @kiview @rnorth how are chances this gets into master or at least the incubator?

**Comment by EnricoMi** [comment]
@kiview I have rebased with master to resolve conflicts in `.github/dependabot.yml`. Any timeline to get this into incubating?

**Comment by eddumelendez** [comment]
Hi, thanks for the contribution and sorry for the delay. Nowadays, Testcontainers offers a [Module Catalog](https://testcontainers.com/modules/). Dgraph can be published on your own and provide an entry in the [community-module-registry](https://github.com/testcontainers/community-module-registry) repository.

**Pull request closed without merging**
