### PR TITLE
WIP Update oracleContainer to use new password and serviceName 

### LINKED ISSUE #2215: OracleContainer needs further configuration
The latest version of oracle database needs a slash between the port and the sid of the jdbcUrl: jdbc:oracle:thin@//[hostname]:[port]/[DB service name]

resources:
https://www.oracle.com/dk/database/technologies/appdev/xe/quickstart.html (under java connection)
https://docs.oracle.com/database/121/JJDBC/urls.htm#BEIDHCBA

Also the SID should be configurable (in the same way as username/password is)

### LINKED ISSUE #2356: OracleContainer allow custom password
Currently the withPassword method on OracleContainer changes the field value but does not actually change the password on the container.

https://github.com/testcontainers/testcontainers-java/blob/2e9adb94ec09c074c43984e14e710daf9d1d6c20/modules/oracle-xe/src/main/java/org/testcontainers/containers/OracleContainer.java#L87-L91

Given that we are supporting the Oracle XE container we should be able to update the password by providing an environment variable to the container in the form:
```
ORACLE_PWD="SecretPassword"
```

See Oracle container documentation here: https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance#running-oracle-database-18c-express-edition-in-a-docker-container

### PR DESCRIPTION
**Pull request by KyleAure**
Fixes #2356 
Fixes #2215

### CODE REVIEW

**Comment by kiview** [comment]
Since we don't have CI for Oracle, I will built the Docker images on my machine and test by hand.

**Comment by kiview** [comment]
`SimpleOracleTest` fails for me with official (self-build) image `oracle/database:18.4.0-xe`:
```
Caused by: java.sql.SQLException: Listener refused the connection with the following error:
ORA-12526, TNS:listener: all appropriate instances are in restricted mode
```
Is this to be expected?

**Comment by KyleAure** [comment]
This is not something I would expect.  I have been testing against an 11g-R2 container and have not run into this. Let me see if I can replicate this using 18c.

**Comment by KyleAure** [comment]
@kiview Looks like I ran into the same error here: 
```
Listener refused the connection with the following error: ORA-12526, TNS:listener: all appropriate instances are in restricted mode 
```
Output from the container indicated that the database had only installed up to 34%
```
[02/17/2020 14:59:31:619 CST] 001 JdbcDatabaseContainer          waitUntilContainerStarted      I Waiting for database connection to become available at jdbc:oracle:thin:system/oracle@localhost:33890:xe using query 'SELECT 1 FROM DUAL'
[02/17/2020 14:59:31:649 CST] 046 OracleTraceTest                oracle                         I ORACLE PASSWORD FOR SYS AND SYSTEM: 6450eba1b853938f
[02/17/2020 14:59:31:780 CST] 046 OracleTraceTest                oracle                         I Specify a password to be used for database accounts. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9]. Note that the same password will be used for SYS, SYSTEM and PDBADMIN accounts:
[02/17/2020 14:59:31:781 CST] 046 OracleTraceTest                oracle                         I Confirm the password:
[02/17/2020 14:59:31:790 CST] 046 OracleTraceTest                oracle                         I Configuring Oracle Listener.
[02/17/2020 14:59:34:865 CST] 046 OracleTraceTest                oracle                         I Listener configuration succeeded.
[02/17/2020 14:59:34:865 CST] 046 OracleTraceTest                oracle                         I Configuring Oracle Database XE.
[02/17/2020 14:59:45:483 CST] 046 OracleTraceTest                oracle                         I Enter SYS user password: 
[02/17/2020 14:59:45:486 CST] 046 OracleTraceTest                oracle                         I  **************** ****
[02/17/2020 14:59:45:487 CST] 046 OracleTraceTest                oracle                         I Enter SYSTEM user password: 
[02/17/2020 14:59:45:489 CST] 046 OracleTraceTest                oracle                         I **************** ****
[02/17/2020 14:59:45:490 CST] 046 OracleTraceTest                oracle                         I Enter PDBADMIN User Password: 
[02/17/2020 14:59:45:492 CST] 046 OracleTraceTest                oracle                         I *************** *
[02/17/2020 14:59:46:139 CST] 046 OracleTraceTest                oracle                         I Prepare for db operation
[02/17/2020 14:59:46:317 CST] 046 OracleTraceTest                oracle                         I 7% complete
[02/17/2020 14:59:46:317 CST] 046 OracleTraceTest                oracle                         I Copying database files
[02/17/2020 15:01:23:732 CST] 046 OracleTraceTest                oracle                         I 29% complete
[02/17/2020 15:01:23:747 CST] 046 OracleTraceTest                oracle                         I Creating and starting Oracle instance
[02/17/2020 15:01:57:977 CST] 046 OracleTraceTest                oracle                         I 30% complete
[02/17/2020 15:02:12:715 CST] 046 OracleTraceTest                oracle                         I 31% complete
[02/17/2020 15:02:12:744 CST] 046 OracleTraceTest                oracle                         I 34% complete
[02/17/2020 15:03:32:745 CST] 001 JdbcDatabaseContainer          waitUntilContainerStarted      I Container is started (JDBC URL: jdbc:oracle:thin:system/oracle@localhost:33890:xe)
```

I am guessing this is likely due to our wait strategy.  We wait for a connection to become available then attempt to call `SELECT 1 FROM DUAL`.  At 34% complete it seems like connection are able to be created but not used.  Hence the error.  

This may be related to #1292

**Comment by kiview** [comment]
@KyleAure thanks for investigating this. 

In the light of #1292 and the fact that we have official images from Oracle, I would propose fixing the `WaitStrategy` to work with the new images (making it `LogMessageWaitStrategy`).

I can take care of this. But this would probably break backwards compatibility to the old (which is [banned](https://hub.docker.com/r/wnameless/oracle-xe-11g-r2) after all).

What do the others think? @rnorth @bsideup

**Comment by kiview** [comment]
Got kind of working waiting strategy, but the image takes 8 minutes to start. Does this even make sense in the context of TC?

```java
    public OracleContainer(String dockerImageName) {
        super(dockerImageName);
        this.waitStrategy = new LogMessageWaitStrategy()
            .withRegEx("DATABASE IS READY TO USE!\\n")
            .withStartupTimeout(Duration.of(12, MINUTES));
    }
```

**Comment by KyleAure** [comment]
Yeah I would be hesitant to break compatibility with oracleinanutshell/oracle-xe-11g and wnameless/docker-oracle-xe-11g since I am sure most people are using those right now.

But I think we should definitely document in our instructions how users can create their own images, and that we recommend building an image with a pre-built database (to alleviate startup time).  If they are following those instructions they can set a password when building their image (in which case this PR is kind of moot).  

Thoughts?

**Comment by kiview** [comment]
In the light of https://twitter.com/geraldvenzl/status/1230673245193539585?s=21 I would prefer to push for the official image. I would personally accept to break compatibility with the `wnameless`, since it is terribly out of date and a grey area after all.

The question is if we try to make the new self=built Oracle image good to use (with e.g. including container volume binding instructions), or if we should wait for the new official image and hope it has faster startup times.

**Comment by MeyerNils** [comment]
Regarding startup times I could imagine a completely different approach for Oracle - see #2369

**Comment by kiview** [comment]
@KyleAure 
After diving a little bit into the internals of the official image I come to realize, that this ENV based approach only works when initializing a new database. This, however, is much to slow with the current official images (as we have already discovered). 
For setting the password of an initialized image, we have to execute a script inside the running container (which we could support in theory).

In the light of these facts, do you think it is okay to close the current PR?

We currently plan to provide a testcontainer oracle-xe image on quay.io that contains an initialized database. I'd prefer if we continue from there.

**Comment by KyleAure** [comment]
Yes, I agree.  Sorry for the runaround.  I am glad to see oracle is officially releasing *something*!  I think if anything we should document that using `withPassword()` (for oracle at least) should be used if you build an oracle image with a custom password... and that it won't actually change the password at runtime (like what happens with postgres)

**Pull request closed without merging**
