### PR TITLE
Refactor TestcontainersConfiguration to allow config by env var

### PR DESCRIPTION
**Pull request by rnorth**
Split out from #3102

### CODE REVIEW

**Review by bsideup — APPROVED** [review]
👍

**Comment by ailjushkin** [comment]
@rnorth Hello, could you please explain why the property for reusing a container could be set only through the env or user property but not through the classpath property? 

@UnstableAPI
    public boolean environmentSupportsReuse() {
        // specifically not supported as an environment variable or classpath property
        return Boolean.parseBoolean(getEnvVarOrUserProperty("testcontainers.reuse.enable", "false"));
    }

**Comment by kiview** [comment]
@ailjushkin Reusable mode is an experimental opt-in feature, and now allowing it on the classpath is done for CI safety reasons. You can find additional explanation here: https://github.com/testcontainers/testcontainers-java/issues/5364#issuecomment-1125907734

**Comment by ailjushkin** [comment]
> @ailjushkin Reusable mode is an experimental opt-in feature, and now allowing it on the classpath is done for CI safety reasons. You can find additional explanation here: https://github.com/testcontainers/testcontainers-java/issues/5364#issuecomment-1125907734

Thanks for the quick answer, I got it

**Pull request merged**
