### PR TITLE
Bump docker java 3.1.4

### PR DESCRIPTION
**Pull request by pedro93**
Bump to docker-java dependency to fix https://github.com/testcontainers/testcontainers-java/issues/1548

Replaces https://github.com/testcontainers/testcontainers-java/pull/1340 since I have no permissions to update that MR.

### CODE REVIEW

**Comment by bsideup** [comment]
I am sorry that we have to bounce back with this one (again), but I see that the methods were added "one by one" instead of **actually** fixing the binary change.

To keep it clear what was **actually** changed, here is a link:
https://diff.revapi.org/?groupId=com.github.docker-java&artifactId=docker-java&old=3.1.0-rc-4&new=3.1.4

Just look for `CreateContainerCmd::` (or `Binary: BREAKING`). 

There are currently 38(!) binary breaking breaking changes between `3.1.0-rc-4` and `3.1.4` that we expect to be reverted, so that we can move forward with the upgrade.

**Comment by pedro93** [comment]
> I am sorry that we have to bounce back with this one (again), but I see that the methods were added "one by one" instead of actually fixing the binary change.

That is a larger scope than what was originally said to me: https://github.com/testcontainers/testcontainers-java/pull/1340#issuecomment-502815121

I do not have the context to perform those changes and know what the consequences would be.

Since I am not the maintainer of either repository nor have the insight to decide whether reverting the binary breaking changes is a good solution forward (reverting breaking changes would be contrary to the direction the docker-java repository is going by definition).

I shall then withdraw from trying to perform these changes.

Thank you for your time on this effort.

**Comment by bsideup** [comment]
Hi @pedro93,

Thanks for the time you spent on it! I took over the effort and submitted https://github.com/docker-java/docker-java/pull/1225

I'm in contact with Docker Java's maintainer and we hope that Testcontainers will receive the latest version of Docker Java very soon :)

**Comment by pedro93** [comment]
Looking forward to it, thank you @bsideup :)

**Pull request closed without merging**
