### PR TITLE
ResourceReaper binding uses dockerConfigHostPath instead of default value

### PR DESCRIPTION
**Pull request by aantoniadisatypon**

### CODE REVIEW

**Comment by kiview** [comment]
LGTM, @rnorth @bsideup, can you have a look?

**Comment by aantoniadisatypon** [comment]
We might need to pass ENV variables to ryukContainer as well so that this container will can use the overridden DOCKER_HOST

**Comment by kiview** [comment]
@aantoniadisatypon  Sorry that the PR was pending so long. LGTM, but can you please rebase?

**Comment by kiview** [comment]
Regarding Ryuk, you are right, but I think the code already handles this:
https://github.com/testcontainers/moby-ryuk/blob/master/main.go#L25

**Comment by bsideup** [comment]
@kiview there are some implications, plz don't merge, I'll try to explain tonight

**Comment by kmehltretter** [comment]
This issue is now bothering me . 
I tried running testcontainers with "rootless docker", but Reaper ryuk is not connecting to the correct unix domain socket

**Pull request closed without merging**
