### PR TITLE
ISSUE-1327 start ambassador only if mapping configured

### LINKED ISSUE #1121: Docker-Compose Wait not being respected
I have a compose file that has a few services but I am generally interested in the database and the webapp primarily.

        new DockerComposeContainer(new File("compose-ca1.yml"))
            .withLocalCompose(true)
            .withLogConsumer("ca1", outputFrame -> System.out.print(((OutputFrame) outputFrame).getUtf8String()))
            .withExposedService("devdb", 3306, Wait.forHealthcheck().withStartupTimeout(ofMinutes(2)))
            .withExposedService("ca1", 8443, Wait.forListeningPort().withStartupTimeout(ofMinutes(2)));

On a Docker Machine setup in Windows I notice that the timeout is not being respected, its not even two minutes and the test fails given something like 

> org.testcontainers.containers.ContainerLaunchException: Aborting attempt to link to container juedehkaec9f_devdb_1 as it is not running
> 	at org.testcontainers.containers.GenericContainer.applyConfiguration(GenericContainer.java:477)

I started traversing through some old bugs and I noticed this https://github.com/testcontainers/testcontainers-java/pull/514/files#r245190284 it may be assuming that we are using the sockets which is not something I am doing on a Docker Machine setup.

Also looking at the code for DockerComposeContainer#start it goes like this

            createServices();
            startAmbassadorContainers();
            waitUntilServiceStarted();

The stack trace noted that it failed on startAmbassadorContainers() which is for socat.  However, I think there should be a check to make sure the services are up because my database takes a bit of time to start up I think the socat creation may be failing there.

### PR DESCRIPTION
**Pull request by ftardif**
fix #1121 
edit: that was a typo, this PR fix: https://github.com/testcontainers/testcontainers-java/issues/1327

### CODE REVIEW

**Comment by bsideup** [comment]
Hi @ftardif,

Thanks a lot for fixing it! Could you please add a simple test to verify the fix?

**Comment by ftardif** [comment]
Do you have a strategy to test these kind of behaviours? I cannot do a unit test by mocking the ambassador generic container because it is instantiated within the class. And I am not too sure how I could do an integration test to verify that socat container is not launched. Any recommendation?

**Comment by bsideup** [comment]
@ftardif AFAIR it will fail if there are no ports exposed, right? Can we test it?

**Comment by ftardif** [comment]
No the idea is to work, but without the socat container, only the ryuk and actual containers unwind from the compose file. When the containers already have host port exposed, we can use these for waiting strategies, hence the basic socat check becomes un relevant.

**Comment by ftardif** [comment]
this PR is meant to fix : https://github.com/testcontainers/testcontainers-java/issues/1327

**Comment by bsideup** [comment]
reported #1331, will merge this one without a test

**Comment by trajano** [comment]
So is #1121 fixed for this is it still a typo?

**Comment by bsideup** [comment]
@ftardif thanks for your contribution! 👍 

@trajano I think #1121 is a different problem

**Comment by trajano** [comment]
OK because it was marked as closed due to this PR.

**Comment by rnorth** [comment]
Releasing this in [1.11.0](https://github.com/testcontainers/testcontainers-java/releases/tag/1.11.0) 🎉

**Pull request merged**
