### PR TITLE
Testcontainer support for dynamodb local containers

### PR DESCRIPTION
**Pull request by bijukunjummen**
Adds in support for DynamoDB Local - https://hub.docker.com/r/amazon/dynamodb-local

### CODE REVIEW

**Comment by bijukunjummen** [comment]
Yes, felt that this is an overkill @rnorth , I think we can close this PR as one of Localstack or Dynamite should be sufficient. @bsideup, localstack uses Dynalite internally also though, not DynamoDB local, per this - https://github.com/localstack/localstack#why-localstack

**Comment by bsideup** [comment]
@bijukunjummen maybe it is outdated?
https://github.com/localstack/localstack/blob/75df19b29afaaf2e10c48013bfc214e650741aec/localstack/services/dynamodb/dynamodb_starter.py#L39
https://github.com/localstack/localstack/blob/66e11a09cbda5c792e417b4b9fa42e39b603fcfb/localstack/constants.py#L73

**Comment by bsideup** [comment]
Ah, seems to be replaced:
https://github.com/localstack/localstack/commit/4b69a89333c3b993da47568717835e52e953a713

**Comment by bijukunjummen** [comment]
Ah, thanks @bsideup, yes totally agreed then, even more so a reason to close this PR :-). Appreciate you and @rnorth looking at the PR.

**Pull request closed without merging**
