### PR TITLE
 Enhancements and Fixes around JDBC URL Based Containers

### LINKED ISSUE #596: Oracle Connection String is not accepted by JDBC Container
Container Database Driver is matching the connection url against a [regex pattern](https://github.com/testcontainers/testcontainers-java/blob/master/modules/jdbc/src/main/java/org/testcontainers/jdbc/ContainerDatabaseDriver.java#L40) - `jdbc:tc:([a-z]+)(:([^:]+))?://[^\\?]+(\\?.*)?` .

This is not accepting Oracle JDBC Connection String of the format - `jdbc:oracle:thin:@myhost:1521:orcl`

This is preventing to use Oracle container with JDBC URL.

### LINKED ISSUE #610: db extra connection params are only passed to the first connection in a pool
if you attempt to use a datasource url with extra params like:

jdbc:tc:postgresql://somehostname:someport/databasename?stringtype=unspecified

the stringtype=unspecified only gets assigned to the very first connection in the pool, all the rest get nothing.

here's a fix:
https://github.com/testcontainers/testcontainers-java/pull/609

### PR DESCRIPTION
**Pull request by manikmagar**
This PR implements #566. 

[Originally implemented in **PR #594 - Allow setting database name and user when using JDBC URL** but that PR branch got messed up during rebasing with upstream, so this New PR replaces it. Check the discussion of #594 for more details. If this is merged, **PR #594 must be closed without merging**.]

1. Extracts out JDBC Url manipulations to a separate class - ConnectionUrl.
2. Adds an overloaded method JdbcDatabaseContainerProvider.newInstance(ConnectionUrl), with default implementation delegating to the existing newInstance(tag) method. 
3. Adds an implementation of newInstance(ConnectionUrl) in MySQLContainerProvider to use Database Name, user, and password from JDBC URL while creating new Container.
4. Added/Updated Test cases for new functionality.
5. Bug Fix: Query Parameters are not used when a connection is created from a cached container. (see [this](https://github.com/testcontainers/testcontainers-java/pull/594#issuecomment-372830327) comment) Fixes #610  
6. Bug Fix: This also fixes #596 and now accepts JDBC Connection Strings for all supported Database Engines.

**Note:** Other Containers Providers such as PostgreSQL will remain unaffected and continue to use earlier implementation of newInstance(tag) due to default delegation, until another implementation is provided.

### CODE REVIEW

**Comment by rnorth** [comment]
This had some merge conflicts, so I've resolved those. As a result, we now have a few more JDBC driver tests than we did previously.

**Comment by manikmagar** [comment]
Thanks @rnorth for merging this with master. There are few test failures in jdbc-test module. I know why they are failing. I'll fix the failing tests in jdbc-test module.

**Comment by manikmagar** [comment]
Ping :) ... Any further thoughts on this one?

**Comment by bsideup** [comment]
@manikmagar FYI I've triggered a re-run of Travis / CircleCI

**Comment by manikmagar** [comment]
Thanks @bsideup. I looked at the logs for failed tests and both looks to be environment related.

**Comment by manikmagar** [comment]
Any thoughts on this one, please? Looking to try Oracle JDBC Driver. (#596 ). Thanks.

**Comment by rnorth** [comment]
Sorry @manikmagar - I'll scoop up all the SQL related tickets on an evening this week and crunch through them. Sorry for the long delay :(

**Comment by manikmagar** [comment]
Thanks @rnorth, I appreciate your time and efforts!

**Comment by rnorth** [comment]
I've rebased onto master - this included updating to be compatible with our change to use a default tag, rather than latest, whenever possible. This had some impact on `JdbcDatabaseContainerProvider` and the JDBC tests, but all is working OK now.

As I've had ample opportunity to read and tweak during the rebasing effort, this LGTM :)

Sorry for taking an eternity to complete this.

**Comment by manikmagar** [comment]
Thank you very much @rnorth for reviewing and rebasing this PR. I am really excited to see these changes are progressing 👍🙂!
  

  
  

  
  
>

**Comment by rnorth** [comment]
Thanks @manikmagar - merged!

**Pull request merged**
