### PR TITLE
Reduce severity of warning for failed auth config lookups (fixes #1399)

### LINKED ISSUE #1399: Is there anything I could do to fix the warning "Failure when attempting to lookup auth config" ?
Hello,

I'm running Testcontainer with maven on Ubuntu 17.04. It works but I get the warning below in bold every time. Is there something that I can do to fix it? Thanks so much!

11:14:50.379381-INFO Loaded org.testcontainers.dockerclient.ProxiedUnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
11:14:50.427417-INFO Will use 'okhttp' transport
11:14:50.883633-INFO Found Docker environment with local Unix socket (via TCP proxy)
11:14:50.885215-INFO Docker host IP address is localhost
11:14:51.012482-INFO Connected to docker:
  Server Version: 17.12.0-ce
  API Version: 1.35
  Operating System: Ubuntu 17.04
  Total Memory: 15934 MB
**11:14:51.041070-WARN Failure when attempting to lookup auth config (dockerImageName: [Ljava.lang.Object;@63a65a25, configFile: {}. Falling back to docker-java default behaviour. Exception message: {}**
11:14:51.571326-INFO Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.698 sec

### PR DESCRIPTION
**Pull request by DevilzOwn**

### CODE REVIEW

**Comment by vcvitaly** [comment]
Fixes https://github.com/testcontainers/testcontainers-java/issues/1399

**Comment by binkley** [comment]
Thank you for this PR -- I can't approve (not a project member), but especially the additional detail on the Docker repo would help me understand the output, and being INFO rather than WARN makes more sense to me.

**Comment by rnorth** [comment]
Build failure seems unrelated. Have raised #3378 to fix.

**Comment by DevilzOwn** [comment]
@rnorth Thanks for fixing the build :). Can you please help in getting this merged?

**Review by rnorth — APPROVED** [review]
LGTM, thanks @DevilzOwn!

**Pull request merged**
