### PR TITLE
Return default for empty environment variable

### LINKED ISSUE #5026: 'EnvironmentAndSystemPropertyClientProviderStrategy' should handle empty DOCKER_HOST
Testcontainers fails to start if DOCKER_HOST is set to an empty string.

Reproducer:
```
export DOCKER_HOST=
// run the tests
```

### PR DESCRIPTION
**Pull request by roulpriya**
Check environment variables and return default if it is empty

Fixes #5026

### CODE REVIEW

**Comment by eddumelendez** [comment]
thanks for your contribution @roulpriya ! Can you run `./gradlew :testcontainers:spotlessApply`, please? that would fix the build

**Comment by roulpriya** [comment]
@eddumelendez Yes, I've done.

**Comment by eddumelendez** [comment]
thank you so much @roulpriya ! this is not merged in `main` branch.

**Comment by roulpriya** [comment]
Thankyou @eddumelendez
Looking forward to contributing more.

**Pull request merged**
