### PR TITLE
Support build args in FROM statement

### LINKED ISSUE #3238: Unable to pre-fetch an image when using build-args in FROM
We are using the following:
```JAVA
new ImageFromDockerfile()
	.withDockerfile(Paths.get("Dockerfile"))
...
```
Dockerfile
```SHELL
ARG tag=latest
FROM maven:3-openjdk-11 AS build-env
# Build
FROM domain.com/package/image:${tag}
# Copy builded stuff into container
```

This throws an exception, as it trys to pre-fetch an image:
```
11:25:48 INFO  [ducttape-0] [ilder.ImageFromDockerfile] Pre-emptively checking local images for 'domain.com/package/image:${tag}', referenced via a Dockerfile. If not available, it will be pulled.  
11:25:48 ERROR [tc-okhttp-stream-1066222696] [nc.ResultCallbackTemplate] Error during callback  
com.github.dockerjava.api.exception.BadRequestException: {"message":"invalid reference format"}

	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:283)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$executeAndStream$4(OkHttpInvocationBuilder.java:317)
	at java.base/java.lang.Thread.run(Thread.java:834)
11:25:48 WARN  [ducttape-0] [ilder.ImageFromDockerfile] Unable to pre-fetch an image (domain.com/package/image:${tag}) depended upon by Dockerfile - image build will continue but may fail. Exception message was: {"message":"invalid reference format"}
```

It would be nice
* if the code which pre-fetches/pulls the dependencies would automatically consider the use of args and either uses them to download the image or simply ignores it
* OR if there is an option to disable the pre-fetching/pulling

### PR DESCRIPTION
**Pull request by Donnerbart**
Resolves #3238
Closes #3922

Since #3922 has merge conflicts, the author is inactive on GitHub for over a year and the provided solution is missing some resolve cases, I've create a new PR which also cleans up some warnings and deprecated code usage in the involved classes.

### CODE REVIEW

**Comment by Donnerbart** [comment]
Hey folks :) Is there anything I can do to move this forward?

Beside the small cleanups and replacement of deprecated API, the actual code for the fix comes from `com.github.dockerjava.core.dockerfile.DockerfileStatement`, so it's a battle proven solution. So I hope this PR is easy to review.

**Comment by Donnerbart** [comment]
Hey folks, is there any chance to get this merged? We still have a workaround in our code base to mitigate this bug :(

**Comment by Donnerbart** [comment]
Hey folks, can we _please_ move this forward somehow? #3238 is still an issue for us.

**Comment by eddumelendez** [comment]
Thanks for the contribution, @Donnerbart! Sorry for the delay reviewing this. I've reverted part of the cleanup done in bcd37abff307415aead91472ba784bda56b611db. One of the changes switch the `deleteOnExit` to the default value `false`. I'm not sure if this is intended.

**Comment by eddumelendez** [comment]
Thanks for your contribution, @Donnerbart !

**Comment by Donnerbart** [comment]
> Thanks for the contribution, @Donnerbart! Sorry for the delay reviewing this. I've reverted part of the cleanup done in [bcd37ab](https://github.com/testcontainers/testcontainers-java/commit/bcd37abff307415aead91472ba784bda56b611db). One of the changes switch the `deleteOnExit` to the default value `false`. I'm not sure if this is intended.

Thanks for the review and merge.

I think you have misread the code here. The actual value of `deleteOnExit` was and is always set from the constructors. And there we set it to `true` if not set otherwise.

There was no need to define a value in the field declaration and have it non-final, just to set it again in the constructor. It's just misleading to have the value set in two places (and have a non-final field for a value that is never changed again). That's exactly the reason why I've changed it.

**Pull request merged**
