### PR TITLE
[Docs] GCP BigQuery: Add Spring Cloud GCP usage

### PR DESCRIPTION
**Pull request by fabriciorby**
Hello, 

I needed to use this BigQuery container and it was really painful to figure out how to configure properly. I could not find any source of bean configuration anywhere, thus I am opening this PR in order to help with the documentation.

Thanks.

### CODE REVIEW

**Comment by eddumelendez** [comment]
Thanks for your contribution. But, our docs are related to Testcontainers and not spring boot itself. Otherwise, we should add docs for every framework integration. Frameworks documentation used to add those when they add those integrations. BigQuery and spring boot example can be linked as in the other one Testcontianers implementation if those examples are maintained. Take into account that BigQuery implementation is not based on a official image but from the community.

You can probably ask the [spring-cloud-gcp](https://github.com/GoogleCloudPlatform/spring-cloud-gcp) team to add more examples in the docs using Testcontainers.

**Comment by fabriciorby** [comment]
@eddumelendez You have a point, I might adapt this for a new PR. Thanks for the quick response. :)

**Comment by eddumelendez** [comment]
Please, consider reaching out the spring cloud gcp. It would be a much better place to add spring related examples that can be maintained by the proper team.

**Comment by fabriciorby** [comment]
@eddumelendez the new PR is about creating the BigQuery instance, I'll just update the way it's being created now in the test file and add it it to the docs, because it's lacking the `setCredentials(NoCredentials.getInstance())`. Which is not related to Spring Boot. Just the official google cloud lib, just like the other examples in the same page. Is it ok?

**Pull request closed without merging**
