### PR TITLE
Adding Alkira as the user

### PR DESCRIPTION
**Pull request by sankee168**
Adding Alkira as the user

### CODE REVIEW

**Review by kiview — APPROVED** [review]

**Comment by kiview** [comment]
Hey @sankee168, just for reference, are you with Alkira?

**Comment by sankee168** [comment]
@kiview Yes. I have been with Alkira since the very beginning.

**Comment by sankee168** [comment]
@kiview Can we get this commit in? Thanks.

**Comment by kiview** [comment]
Sure, thanks for creating the PR and for using Testcontainers 🙂

**Pull request merged**
