### PR TITLE
Enable line terminator matching for LogMessageWaitStrategy

### PR DESCRIPTION
**Pull request by bengtbrodersen0042**
Enable line terminator matching to make  expressions like ".*" matching even the end of a log line e.g. "waiting for connections on port 20017\n"

### CODE REVIEW

**Comment by bengtbrodersen0042** [comment]
Any thoughts on this?

**Comment by bsideup** [comment]
Hi @bengtbrodersen0042,

Could you please add tests for it?

**Comment by bengtbrodersen0042** [comment]
I had to adjust a test only.

**Comment by rnorth** [comment]
I guess I'd just like to check that people won't have problems if they still have the line terminator in their patterns. What happens if people _don't_ update their tests?

It would be sad if this were a breaking change.

**Comment by rnorth** [comment]
I'm just going to add an additional test to make sure both cases are covered - looking good though.

**Comment by rnorth** [comment]
I've pushed a commit with additional test cases.

**Comment by rnorth** [comment]
I'm going to ignore the failing Travis test - it looks like Travis has gotten confused due to me mistakenly pushing a copy of this PR into a branch in the main repo.

**Comment by rnorth** [comment]
Released in [1.10.4](https://github.com/testcontainers/testcontainers-java/releases/tag/1.10.4)!

Thanks for the contribution!

**Pull request merged**
