### PR TITLE
Add compatibility with selenium greater than 3.X

### PR DESCRIPTION
**Pull request by jlamaille**

### CODE REVIEW

**Comment by jlamaille** [comment]
Hi @bsideup 
I had thought about it but the mock part of the classpath seemed a little complex.
I can add TUs on the reading part of the inputStream, it could already be pretty good ?

**Comment by bsideup** [comment]
@jlamaille yeah, I think you can just extract `getVersionFromManifest(Manifest manifest)` to avoid IO and focus on the business logic part of it

**Comment by jlamaille** [comment]
That's exactly what I planned to do.
As soon as I find a little time, I push that.

**Comment by jlamaille** [comment]
I added 2 unit tests for detection of Selenium versions above / below 3

**Comment by bsideup** [comment]
@jlamaille merged, thanks! 💪

**Pull request merged**
