### PR TITLE
Make exposeHostPort reusable

### PR DESCRIPTION
**Pull request by TomDeBacker**
#3457
Container can now start when using withReuse(true) and TestContainers.exposeHostPort(). Simple if check added: if reuse is true don't call connectToPortForwardingNetwork()

### CODE REVIEW

**Review by eddumelendez — CHANGES_REQUESTED** [review]
PR is introducing unnecessary changes. Please, clean it up.

**Comment by TomDeBacker** [comment]
@eddumelendez This should remove the whitespace changes, I added some extra asserts in the test.

**Comment by TomDeBacker** [comment]
Not exactly sure what's going on yet. 
```
Gradle Test Executor 1 > org.testcontainers.containers.ExposedHostTest > testExposedHostPortIsReusable STARTED
Gradle Test Executor 1 > org.testcontainers.containers.ExposedHostTest > testExposedHostPortIsReusable PASSED
```

Locally these tests seem to work fine.
```

22:18:59.699 INFO  🐳 [testcontainers/sshd:1.1.0] - Container testcontainers/sshd:1.1.0 started in PT0.369837207S
22:18:59.776 INFO  🐳 [alpine:3.16] - Creating container for image: alpine:3.16
22:18:59.851 INFO  🐳 [alpine:3.16] - Container alpine:3.16 is starting: 86e26a791c6448301c3880d302f3707e558143c2482549d8e506c8e52b495d67
22:19:00.067 INFO  🐳 [alpine:3.16] - Container alpine:3.16 started in PT0.291663502S
22:19:00.135 INFO  🐳 [alpine:3.16] - Creating container for image: alpine:3.16
22:19:00.142 INFO  🐳 [alpine:3.16] - Reusing container with ID: 86e26a791c6448301c3880d302f3707e558143c2482549d8e506c8e52b495d67 and hash: 09a6d05200a2b3e9cfaa840e5b7d715d193350ff
22:19:00.143 INFO  🐳 [alpine:3.16] - Reusing existing container (86e26a791c6448301c3880d302f3707e558143c2482549d8e506c8e52b495d67) and not creating a new one
22:19:00.144 INFO  🐳 [alpine:3.16] - Container alpine:3.16 started in PT0.009484268S
```

**Comment by TomDeBacker** [comment]
@eddumelendez I've made the changes you requested

**Comment by nburkley** [comment]
@eddumelendez Any updates on this PR? -We're also running into this issue. Thanks in advance!

**Pull request closed without merging**
