### PR TITLE
Removed deprecated methods and undeclared transitive dependency to AWS SDK v1

### LINKED ISSUE #4279: java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentials with localstack module and AWS SDK2
When using the AWS SDK v2 the `com.amazonaws.auth.AWSCredentials` class is not present and a java.lang.NoClassDefFoundError is thrown.

Imho either the local stack module should declare a dependency on the AWS SDK v1 or not use the classes at all. (I'd prefer the latter). 

my current workaround, is to add the classes just for tests:
```
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-core</artifactId>
            <version>1.11.959</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

### PR DESCRIPTION
**Pull request by AB-xdev**
Fixes #4279.

The problem:
The localstack module has an undeclared dependency to parts of the AWS SDK v1 which causes the above issue.

While the methods have been deprecated with #5489, this still doesn't fix the class loading problems.

The fix:
The removal of the deprecated methods, corresponding imports and dependencies should fix the class loading problems.

### CODE REVIEW

**Comment by eddumelendez** [comment]
thanks for the PR @AB-xdev ! We are not planning to remove it for now but for 2.0.

**Comment by eddumelendez** [comment]
Thanks for your contribution, @AB-xdev ! This is now merged in `main` and it will be part of the next release.

**Comment by kkocel** [comment]
@eddumelendez do you know when it will be released? I use AWS SDK v2 and I would like not to have import v1.

**Comment by asafch** [comment]
Hi @eddumelendez I couldn't find any mention in this repo of following semver or any other versioning policy, can you please direct me to it? I'm asking because this PR was merged as part of the 1.18.0 release, and the removal of the deprecated methods is a breaking change. Just want to understand how I should interpret the release notes when considering upgrading a specific module version in my projects.

**Pull request merged**
