### PR TITLE
Combined dependencies PR

### PR DESCRIPTION
**Pull request by kiview**
Combining multiple dependencies PRs into one.

<details>
<summary>Instructions for merging</summary>

* **Use a merge commit**, so that GitHub will mark all original PRs as merged.
* If your repository does not have merge commits enabled, please temporarily enable them in settings. Tick `Allow merge commits` in the repository settings.
* When ready, merge this PR using `Create a merge commit`.

</details>

## Combined PRs

* Bump com.gradle.enterprise.gradle.plugin from 3.10.1 to 3.10.2 (#5578) @dependabot
* Bump postgresql from 42.3.6 to 42.4.0 in /modules/cockroachdb (#5575) @dependabot
* Bump azure-cosmos from 4.30.0 to 4.32.1 in /modules/azure (#5574) @dependabot
* Bump mongodb-driver-sync from 4.6.0 to 4.6.1 in /modules/mongodb (#5573) @dependabot
* Bump amqp-client from 5.14.2 to 5.15.0 in /modules/rabbitmq (#5572) @dependabot
* Bump google-cloud-pubsub from 1.119.0 to 1.120.0 in /modules/gcloud (#5571) @dependabot
* Bump google-cloud-bigtable from 2.8.0 to 2.9.0 in /modules/gcloud (#5570) @dependabot
* Bump client-java from 15.0.1 to 16.0.0 in /modules/k3s (#5569) @dependabot
* Bump google-cloud-datastore from 2.7.0 to 2.10.0 in /modules/gcloud (#5568) @dependabot
* Bump google-cloud-spanner from 6.25.5 to 6.25.7 in /modules/gcloud (#5567) @dependabot
* Bump hivemq-extension-sdk from 4.8.1 to 4.8.2 in /modules/hivemq (#5565) @dependabot
* Bump reactor-core from 3.4.18 to 3.4.19 in /modules/r2dbc (#5563) @dependabot
* Bump com.gradle.enterprise.gradle.plugin from 3.10 to 3.10.2 in /examples (#5559) @dependabot
* Bump postgresql from 42.3.6 to 42.4.0 in /examples (#5558) @dependabot
* Bump assertj-core from 3.22.0 to 3.23.1 in /examples (#5556) @dependabot
* Bump cucumber-java from 7.2.3 to 7.4.1 in /examples (#5554) @dependabot
* Bump actions/cache from 3.0.3 to 3.0.4 (#5552) @dependabot
* Bump gradle-update/update-gradle-wrapper-action from 1.0.17 to 1.0.18 (#5551) @dependabot
* Bump peter-evans/create-pull-request from 4.0.3 to 4.0.4 (#5550) @dependabot
* Bump s3 from 2.17.204 to 2.17.224 in /modules/localstack (#5547) @dependabot
* Bump amqp-client from 5.14.2 to 5.15.0 in /core (#5546) @dependabot
* Bump aws-java-sdk-sqs from 1.12.233 to 1.12.253 in /modules/localstack (#5545) @dependabot
* Bump cucumber-junit from 7.3.4 to 7.4.1 in /examples (#5544) @dependabot
* Bump tomcat-jdbc from 10.0.21 to 10.0.22 in /modules/jdbc (#5538) @dependabot
* Bump rest-assured from 5.1.0 to 5.1.1 in /modules/vault (#5537) @dependabot
* Bump transport from 7.17.4 to 7.17.5 in /modules/elasticsearch (#5535) @dependabot
* Bump r2dbc-mariadb from 1.0.3 to 1.1.2 in /modules/mariadb (#5534) @dependabot
* Bump elasticsearch-rest-client from 8.2.2 to 8.3.1 in /modules/elasticsearch (#5533) @dependabot

### CODE REVIEW

**Comment by kiview** [comment]
There seems to be an issue with #5534: https://github.com/testcontainers/testcontainers-java/runs/7160766788?check_suite_focus=true#step:5:22

**Comment by eddumelendez** [comment]
the extension checks the status via GH API and for some reason it doesn't return failed status in some cases. I had to check mannually last time `gh pr checks` and re-run those that failed but return success, so, they can be skip.

**Comment by eddumelendez** [comment]
this is the output for `gh pr checks 5534` and that's the reason why it was included 

```
All checks were successful
0 failing, 27 successful, 2 skipped, and 0 pending checks
```

**Comment by eddumelendez** [comment]
I re-run the checks for #5534 and now it is returning

```
Some checks were not successful
1 failing, 26 successful, 2 skipped, and 0 pending checks
```

So, the PR should not be taken by the gh combine pr extension

**Comment by kiview** [comment]
Thanks for the investigation @eddumelendez. As I see, there is nothing we can do from the side of the extension, since the GH API is somehow returning the wrong response, correct?

I'll just close this PR, easier to create a new one.

**Pull request closed without merging**
