### PR TITLE
Always replace containerInstance when a DockerComposeContainer is initialized

### LINKED ISSUE #7443: [Bug]: DockerComposeContainer with healthcheck wait strategy fails for successive tests
### Module

Core

### Testcontainers version

1.19.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host Arch

64-bit

### Docker version

```shell
Client:
 Cloud integration: v1.0.35-desktop+001
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:36:24 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.22.0 (117440)
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

Consider this setup:
`docker-compose.yml`
```
version: "3.9"
services:
  oracle-db:
    image: liantisit/gvenzl-oracle-xe:18-slim
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=phoenix
    volumes:
      - ./sql:/container-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "/opt/oracle/healthcheck.sh" ]
      interval: 2s
```
`DockerComposeIntegrationTest.java`
```
package be.liantis.medical.followup.removeme;

import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.testcontainers.containers.DockerComposeContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.io.File;
import java.time.Duration;

@SpringBootTest
@ActiveProfiles("docker")
@Testcontainers
public abstract class DockerComposeIntegrationTest {

    @Container
    public static final DockerComposeContainer DOCKER_COMPOSE_CONTAINER;

    static {
        DOCKER_COMPOSE_CONTAINER = new DockerComposeContainer<>(new File("docker/lala/docker-compose.yml"))
                .withLocalCompose(true)
                .waitingFor("oracle-db", Wait.forHealthcheck().withStartupTimeout(Duration.ofMinutes(5)));
        DOCKER_COMPOSE_CONTAINER.start();
    }

}
```
`FirstIntegrationTest.java`
```
public class FirstIntegrationTest extends DockerComposeIntegrationTest {

    @Test
    void test_one() {
        System.err.println("Lala");
    }

}
```
`SecondIntegrationTest.java`
```
public class SecondIntegrationTest extends DockerComposeIntegrationTest {

    @Test
    void test_two() {
        System.err.println("Lala");
    }

}
```
When I run the suite where these two test classes are present the second one will fail to start.
The tests are in JUnit 5.
See additional information for more in depth info on what I think is going wrong.
**Note** The code and logs are adjusted slightly because of company policy
Logging is set to TRACE

### Relevant log output

```shell
FirstIntegrationTest.java:

16:01:24.754 [main] INFO  o.s.t.c.s.AnnotationConfigContextLoaderUtils - Could not detect default configuration classes for test class [be.liantis.medical.followup.removeme.SecondIntegrationTest]: SecondIntegrationTest does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
16:01:24.921 [main] INFO  o.s.b.t.c.SpringBootTestContextBootstrapper - Found @SpringBootConfiguration be.liantis.medical.followup.MedicalFollowUpServiceApplication for test class be.liantis.medical.followup.removeme.SecondIntegrationTest
16:01:25.126 [main] INFO  o.t.utility.ImageNameSubstitutor - Found configured ImageNameSubstitutor: Liantis private registry image name substitutor
16:01:25.128 [main] INFO  o.t.utility.ImageNameSubstitutor - Image name substitution will be performed by: Chained substitutor of 'DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')' and then 'Liantis private registry image name substitutor'
16:01:25.360 [main] INFO  o.t.d.DockerClientProviderStrategy - Loaded org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
16:01:25.606 [main] INFO  o.t.d.DockerClientProviderStrategy - Found Docker environment with local Npipe socket (npipe:////./pipe/docker_engine)
16:01:25.607 [main] INFO  o.testcontainers.DockerClientFactory - Docker host IP address is localhost
16:01:25.614 [main] INFO  o.testcontainers.DockerClientFactory - Connected to docker: 
  Server Version: 24.0.5
  API Version: 1.43
  Operating System: Docker Desktop
  Total Memory: 11977 MB
16:01:25.614 [main] INFO  o.t.utility.RyukResourceReaper - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
16:01:25.615 [main] INFO  o.testcontainers.DockerClientFactory - Checking the system...
16:01:25.616 [main] INFO  o.testcontainers.DockerClientFactory - ✔︎ Docker server version should be at least 1.6.0
16:01:25.620 [main] INFO  o.t.utility.ImageNameSubstitutor - Using liantisit/testcontainers-ryuk:0.5.1 as a substitute image for testcontainers/ryuk:0.5.1 (using image substitutor: Liantis private registry image name substitutor)
16:01:25.634 [main] INFO  t.l.5.1 - Creating container for image: liantisit/testcontainers-ryuk:0.5.1
16:01:36.281 [main] INFO  t.l.5.1 - Container liantisit/testcontainers-ryuk:0.5.1 is starting: 6d0c23e74dd225239ccaaa93dc5d3341323bfdfebea6fed204f13fcbc7d45fef
16:01:36.557 [main] INFO  t.l.5.1 - Container liantisit/testcontainers-ryuk:0.5.1 started in PT10.9397336S
16:01:36.566 [main] INFO  o.t.containers.ComposeDelegate - Preemptively checking local images for 'liantisit/gvenzl-oracle-xe:18-slim', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
16:01:36.571 [main] INFO  tc.docker-compose.exe - Local Docker Compose is running command: up -d
16:01:36.950 [Thread-23] INFO  tc.docker-compose.exe -  Network qxpgbuhudxa8_default  Creating
16:01:36.983 [Thread-23] INFO  tc.docker-compose.exe -  Network qxpgbuhudxa8_default  Created
16:01:36.983 [Thread-23] INFO  tc.docker-compose.exe -  Container qxpgbuhudxa8-oracle-db-1  Creating
16:01:37.050 [Thread-23] INFO  tc.docker-compose.exe -  Container qxpgbuhudxa8-oracle-db-1  Created
16:01:37.056 [Thread-23] INFO  tc.docker-compose.exe -  Container qxpgbuhudxa8-oracle-db-1  Starting
16:01:37.276 [Thread-23] INFO  tc.docker-compose.exe -  Container qxpgbuhudxa8-oracle-db-1  Started
16:01:37.319 [main] INFO  tc.docker-compose.exe - Docker Compose has finished running
16:02:04.217 [main] INFO  o.t.containers.ComposeDelegate - Preemptively checking local images for 'liantisit/gvenzl-oracle-xe:18-slim', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
16:02:04.222 [main] INFO  tc.docker-compose.exe - Local Docker Compose is running command: up -d
16:02:04.736 [Thread-25] INFO  tc.docker-compose.exe -  Container qxpgbuhudxa8-oracle-db-1  Running
16:02:04.787 [main] INFO  tc.docker-compose.exe - Docker Compose has finished running


...

16:02:20.709 [main] INFO  tc.docker-compose.exe - Local Docker Compose is running command: down -v
16:02:20.709 [main] DEBUG o.t.s.o.z.exec.ProcessExecutor - Executing [docker-compose.exe, down, -v] in C:\Users\jeno.dekeyzer\git\medical-follow-up-service\docker\lala with environment {DOCKER_HOST=npipe:////./pipe/docker_engine, COMPOSE_PROJECT_NAME=qxpgbuhudxa8, COMPOSE_FILE=C:\Users\jeno.dekeyzer\git\medical-follow-up-service\docker\lala\docker-compose.yml}.
16:02:20.731 [main] DEBUG o.t.s.o.z.exec.ProcessExecutor - Started Process[pid=9716, exitValue="not exited"]
16:02:20.733 [Thread-32] TRACE o.t.s.o.z.exec.stream.StreamPumper - org.testcontainers.shaded.org.zeroturnaround.exec.stream.StreamPumper@1f197ed started.
16:02:20.733 [Thread-33] TRACE o.t.s.o.z.exec.stream.StreamPumper - org.testcontainers.shaded.org.zeroturnaround.exec.stream.StreamPumper@8a5089b started.
16:02:21.361 [Thread-33] INFO  tc.docker-compose.exe -  Container qxpgbuhudxa8-oracle-db-1  Stopping
16:02:31.560 [Thread-33] INFO  tc.docker-compose.exe -  Container qxpgbuhudxa8-oracle-db-1  Stopped
16:02:31.560 [Thread-33] INFO  tc.docker-compose.exe -  Container qxpgbuhudxa8-oracle-db-1  Removing
16:02:31.816 [Thread-33] INFO  tc.docker-compose.exe -  Container qxpgbuhudxa8-oracle-db-1  Removed
16:02:31.819 [Thread-33] INFO  tc.docker-compose.exe -  Network qxpgbuhudxa8_default  Removing
16:02:31.880 [Thread-33] INFO  tc.docker-compose.exe -  Network qxpgbuhudxa8_default  Removed
16:02:31.922 [Thread-33] TRACE o.t.s.o.z.exec.stream.StreamPumper - org.testcontainers.shaded.org.zeroturnaround.exec.stream.StreamPumper@8a5089b finished.
16:02:31.922 [Thread-32] TRACE o.t.s.o.z.exec.stream.StreamPumper - org.testcontainers.shaded.org.zeroturnaround.exec.stream.StreamPumper@1f197ed finished.
16:02:31.923 [main] DEBUG o.t.s.o.z.exec.WaitForProcess - Process[pid=9716, exitValue=0] stopped with exit code 0
16:02:31.924 [main] TRACE o.t.s.o.z.e.stream.PumpStreamHandler - Joining output thread Thread[Thread-32,5,]...
16:02:31.924 [main] TRACE o.t.s.o.z.e.stream.PumpStreamHandler - Joining error thread Thread[Thread-33,5,]...
16:02:31.924 [main] TRACE o.t.s.o.z.e.stream.PumpStreamHandler - Flushing output stream org.testcontainers.shaded.org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream@472c5608...
16:02:31.924 [main] TRACE o.t.s.o.z.e.stream.PumpStreamHandler - Flushing error stream org.testcontainers.shaded.org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream@5e0fbfb6...
16:02:31.924 [main] INFO  tc.docker-compose.exe - Docker Compose has finished running

SecondIntegrationTest.java:

16:02:31.931 [main] INFO  o.t.containers.ComposeDelegate - Preemptively checking local images for 'liantisit/gvenzl-oracle-xe:18-slim', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
16:02:31.931 [testcontainers-ryuk] DEBUG o.t.utility.ResourceReaper - Sending 'label=com.docker.compose.project%3Dqxpgbuhudxa8' to Ryuk
16:02:31.931 [main] DEBUG o.t.images.AbstractImagePullPolicy - Using locally available and not pulling image: liantisit/gvenzl-oracle-xe:18-slim
16:02:31.932 [testcontainers-ryuk] DEBUG o.t.utility.RyukResourceReaper - Received 'ACK' from Ryuk
16:02:31.934 [main] INFO  tc.docker-compose.exe - Local Docker Compose is running command: up -d
16:02:31.934 [main] DEBUG o.t.s.o.z.exec.ProcessExecutor - Executing [docker-compose.exe, up, -d] in C:\Users\jeno.dekeyzer\git\medical-follow-up-service\docker\lala with environment {DOCKER_HOST=npipe:////./pipe/docker_engine, COMPOSE_PROJECT_NAME=qxpgbuhudxa8, COMPOSE_FILE=C:\Users\jeno.dekeyzer\git\medical-follow-up-service\docker\lala\docker-compose.yml}.
16:02:31.944 [main] DEBUG o.t.s.o.z.exec.ProcessExecutor - Started Process[pid=16396, exitValue="not exited"]
16:02:31.945 [Thread-34] TRACE o.t.s.o.z.exec.stream.StreamPumper - org.testcontainers.shaded.org.zeroturnaround.exec.stream.StreamPumper@66b57d13 started.
16:02:31.945 [Thread-35] TRACE o.t.s.o.z.exec.stream.StreamPumper - org.testcontainers.shaded.org.zeroturnaround.exec.stream.StreamPumper@3d34a14d started.
16:02:32.280 [Thread-35] INFO  tc.docker-compose.exe -  Network qxpgbuhudxa8_default  Creating
16:02:32.312 [Thread-35] INFO  tc.docker-compose.exe -  Network qxpgbuhudxa8_default  Created
16:02:32.312 [Thread-35] INFO  tc.docker-compose.exe -  Container qxpgbuhudxa8-oracle-db-1  Creating
16:02:32.353 [Thread-35] INFO  tc.docker-compose.exe -  Container qxpgbuhudxa8-oracle-db-1  Created
16:02:32.358 [Thread-35] INFO  tc.docker-compose.exe -  Container qxpgbuhudxa8-oracle-db-1  Starting
16:02:32.559 [Thread-35] INFO  tc.docker-compose.exe -  Container qxpgbuhudxa8-oracle-db-1  Started
16:02:32.604 [Thread-35] TRACE o.t.s.o.z.exec.stream.StreamPumper - org.testcontainers.shaded.org.zeroturnaround.exec.stream.StreamPumper@3d34a14d finished.
16:02:32.604 [Thread-34] TRACE o.t.s.o.z.exec.stream.StreamPumper - org.testcontainers.shaded.org.zeroturnaround.exec.stream.StreamPumper@66b57d13 finished.
16:02:32.605 [main] DEBUG o.t.s.o.z.exec.WaitForProcess - Process[pid=16396, exitValue=0] stopped with exit code 0
16:02:32.605 [main] TRACE o.t.s.o.z.e.stream.PumpStreamHandler - Joining output thread Thread[Thread-34,5,]...
16:02:32.605 [main] TRACE o.t.s.o.z.e.stream.PumpStreamHandler - Joining error thread Thread[Thread-35,5,]...
16:02:32.605 [main] TRACE o.t.s.o.z.e.stream.PumpStreamHandler - Flushing output stream org.testcontainers.shaded.org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream@5ca64b79...
16:02:32.605 [main] TRACE o.t.s.o.z.e.stream.PumpStreamHandler - Flushing error stream org.testcontainers.shaded.org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream@422179c7...
16:02:32.605 [main] INFO  tc.docker-compose.exe - Docker Compose has finished running

...

Constant spam of these two lines until it times out:

16:02:36.588 [ducttape-1] DEBUG o.t.s.c.g.d.c.command.AbstrDockerCmd - Cmd: 1a07b88400276a0ddac342211f5eb45c366624638839378458b16d51a293332e,false
16:02:36.588 [ducttape-1] DEBUG o.t.s.c.g.d.c.e.InspectContainerCmdExec - GET: DefaultWebTarget{path=[/containers/1a07b88400276a0ddac342211f5eb45c366624638839378458b16d51a293332e/json], queryParams={}}
```

### Additional Information

When I dove a bit deeper I noticed the wait strategy was still checking on an old container id (the container from the first test).
In `ContainerState.java`
image
and in `DockerComposeContainer.java` we do this:
```
    private void createServiceInstance(Container container) {
        String serviceName = getServiceNameFromContainer(container);
        final ComposeServiceWaitStrategyTarget containerInstance = new ComposeServiceWaitStrategyTarget(
            dockerClient,
            container,
            ambassadorContainer,
            ambassadorPortMappings.getOrDefault(serviceName, new HashMap<>())
        );

        String containerId = containerInstance.getContainerId();
        if (tailChildContainers) {
            followLogs(containerId, new Slf4jLogConsumer(log).withPrefix(container.getNames()[0]));
        }
        //follow logs using registered consumers for this service
        logConsumers
            .getOrDefault(serviceName, Collections.emptyList())
            .forEach(consumer -> followLogs(containerId, consumer));
        serviceInstanceMap.putIfAbsent(serviceName, containerInstance);
    }
```
Where `serviceInstanceMap.putIfAbsent(serviceName, containerInstance);` should probably be `serviceInstanceMap.put(serviceName, containerInstance);` since the containerInstance could be a new container?

Because of this any wait strategy that involves the container itself (f.e. forSuccessfulCommand as well) will fail.

### Workaround

I fixed this with a hacky fix by clearing `serviceInstanceMap` after each test via reflection, so by adding this to my 

For versions older than 1.19:
DockerComposeIntegrationTest
```
    @AfterAll
    public static void afterAll() throws NoSuchFieldException, IllegalAccessException {
        Field privateField = DockerComposeContainer.class.getDeclaredField("serviceInstanceMap");
        privateField.setAccessible(true);
        privateField.set(DOCKER_COMPOSE_CONTAINER, new ConcurrentHashMap<>());
    }
```
and after 1.19
```
    @AfterAll
    public static void afterAll() {
        Object field = ReflectionTestUtils.getField(DOCKER_COMPOSE_CONTAINER, "composeDelegate");
        ReflectionTestUtils.setField(field, "serviceInstanceMap", new ConcurrentHashMap<>());
    }
```

### PR DESCRIPTION
**Pull request by JenoDK**
Fix #7443

### CODE REVIEW

**Comment by eddumelendez** [comment]
I don't think adding an example would be the best way to test it. If we want to catch the regression the test should be added in `core` folder.

**Comment by JenoDK** [comment]
Any update on this?

**Comment by eddumelendez** [comment]
Hi @JenoDK, sorry for the delay. Can you please remove the changes in examples folder because you already add some tests in core folder? Also, apply `./gradlew sportlessApply` to apply format. One last thing, Can you use a branch different than `main`, so, if any change is needed I can submit changes to your branch? LMK if you can perform those changes. Otherwise, I can submit one new PR base on yours. TIA

**Comment by eddumelendez** [comment]
Closing in favor of #9370

**Pull request closed without merging**
