### PR TITLE
Change docker command of cockroachDB module

### LINKED ISSUE #3571: Breaking change in CockroachDB CLI interface for versions 20.2+.*
Hi,

I have tried using versions 20.2.0 and 20.2.2 of CockroachDB with CockroachContainer and sadly the container crashes with the following output:

```
ERROR: no --join flags provided to 'cockroach start'

HINT: Consider using 'cockroach init' or 'cockroach start-single-node' instead

Failed running "start"
```

Testcontainers itself hangs on this log line:

`[2020-12-08 17:27:02,603] [INFO] [🐳 [cockroachdb/cockroach:v20.2.0]] [] [ScalaTest-run] - Waiting for database connection to become available at jdbc:postgresql://localhost:32830/postgres?reWriteBatchedInserts=true using query 'SELECT 1' MDC: {}` 

but doesn't fail even though the container itself is EXITED(1). It then assumes everything is fine and continues the test framework execution.

### PR DESCRIPTION
**Pull request by giger85**
This PR resolves #3571 

### Caveat
- Before `v19.1.x` version, `start-single-node` command does not work.

### CODE REVIEW

**Comment by giger85** [comment]
Is there anybody to review this PR?

**Review by rnorth — APPROVED** [review]
EDIT: accidentally clicked the approve button 😬

**Review by rnorth — CHANGES_REQUESTED** [review]
This is going to be problematic - it will mean that people who are using the default constructor in their tests will suddenly receive a different version of the container.

This is outlined further in #3381.

Also, we'll have a problem if `start-single-node` is not backwards compatible with older versions if CockroachDB. We can't break peoples' tests if they explicitly need to use older versions. Is it backwards compatible?

**Comment by giger85** [comment]
@rnorth 
As #3608, current default tag version (v19.1.x) reached EOL.
- https://www.cockroachlabs.com/docs/releases/release-support-policy

Since this module is incubating module, I thought this change is acceptable.
But `start-single-node` is not backward compatible command, I will try to find backward compatible solution.

Thanks for your reaview.

**Comment by bsideup** [comment]
@rnorth given the deprecated version and default tag being changed, I think we're good to go :) Will merge :)

**Review by bsideup — APPROVED** [review]

**Comment by giger85** [comment]
@bsideup 
Thanks for your review.
This change helps for me :)

**Pull request merged**
