### PR TITLE
use version 1.2.3 of logback-classic to stay up to date

### PR DESCRIPTION
**Pull request by dbyron0**
yet another dependency bump to keep up.  See https://logback.qos.ch/news.html for background and https://docs.google.com/spreadsheets/d/1cpb5D7qnyye4W0RTlHUnXedYK98catNZytYIu5D91m0/edit#gid=0 for performance changes.

### CODE REVIEW

**Comment by rnorth** [comment]
Travis failure looks unrelated - have retriggered.
Thanks for this.

**Comment by dbyron0** [comment]
Glad the tests are passing.

**Comment by dbyron0** [comment]
Happy to squash the commits when the time comes.

**Comment by rnorth** [comment]
Squashing and merging - looks good to me. Thank you!

**Pull request merged**
