### PR TITLE
First working Sybase version

### PR DESCRIPTION
**Pull request by mcsnolte**
Copied from PostgreSQL

### CODE REVIEW

**Comment by mnhock** [comment]
There are any plans to integrate sybase support?

**Comment by nekperu15739** [comment]
Hi, why this changes were not integrated?

**Comment by mcsnolte** [comment]
@nekperu15739 one thing that will need to be reconsidered is what to use for a Docker image.  [The one I found](https://github.com/testcontainers/testcontainers-java/pull/745/files#diff-21dd798edbbed0562425495fd47f4e48R14) isn't officially supported, it's just an image I found searching on Docker hub that worked.

**Comment by nekperu15739** [comment]
Hi @mcsnolte, thats completely true, there is no official image, however, at least have and sample using sybase db will be enough. I take the code on this pull and use to make my own develop to do an integration test.

**Comment by st6ph** [comment]
Hi, I'd also be interested to know if there is any plan of supporting Sybase in Testcontainers ?

**Pull request closed without merging**
