### PR TITLE
Example and docs for ability to copy to and from container for #1164

### PR DESCRIPTION
**Pull request by sumitanvekar**
Created example to demonstrate ability to copy to and from container using Generic Container.
Added example into advanced_options section.

Created for #1164

### CODE REVIEW

**Comment by rnorth** [comment]
This is cool, thank you @sumitanvekar!

I think my main item of feedback would be to ask for this to appear in the `features/files.md` docs page - it should be its own section in the 'Files and volumes' page.

**Comment by sumitanvekar** [comment]
@rnorth moved docs to files.md as per your comment. Thanks for your review!

**Comment by sumitanvekar** [comment]
Couple tests fails for no apparent reason (from logs, they seemed to be flaky tests). So, I did an empty commit to trigger checks again.

**Comment by bsideup** [comment]
@sumitanvekar please do not trigger full CI if you see some flaky tests, it creates a big load on our CI environments.
Instead, we will rerun the tests of that particular module when we see it during the review.

**Comment by sumitanvekar** [comment]
@bsideup I am not sure if we should use core test class for documentation since they will get polluted with commented code blocks which are required for documentation. However, if we are planning to get rid of all docs example code to avoid duplication, I will update pr with your recommendations.

On a separate note, do you want to add a section in contributing.md to mention about the flaky tests and process for that? That will help newbies. Happy to do a separate pr for it.

**Comment by rnorth** [comment]
Looks like there are some missing imports in `CopyFileToContainerTest`

**Comment by rnorth** [comment]
I've pushed fixed imports to the source branch.

**Comment by sumitanvekar** [comment]
@rnorth @bsideup any chance this can get merged? Or does it need something?

**Comment by rnorth** [comment]
Let's merge it - sorry @sumitanvekar that this has taken so long.

**Comment by rnorth** [comment]
Ohoh, this has broken our build on Windows. I'll revert, and fix up.

**Pull request merged**
