### PR TITLE
toxiproxy: enable/disable methods

### PR DESCRIPTION
**Pull request by sullis**
- enable method:  enable the Proxy
- disable method: disable the Proxy

### CODE REVIEW

**Comment by sullis** [comment]
@bsideup  WDYT?

**Comment by sullis** [comment]
WDYT? @rnorth

**Comment by sullis** [comment]
WDYT? @bsideup

**Comment by bsideup** [comment]
@sullis Starting with #3454, a user can create a ToxyProxy client and use any method available on it, which is the preferred way. Thanks for working on it tho! 👍

**Pull request closed without merging**
