### PR TITLE
Switch from AdoptOpenJDK to Temurin and latest JDK 8.

### PR DESCRIPTION
**Pull request by pioorg**
This change is for migrating from AdoptOpenJDK to Eclipse Temurin.
Perhaps going for the latest Java 8 version again is worth considering?

### CODE REVIEW

**Comment by kiview** [comment]
@rnorth switched to the pinned version in this commit:
https://github.com/testcontainers/testcontainers-java/commit/669cc53419c30b7d211f44fb93802a34729b8c20

But I can't remember any discussion in favor of pinning to an actual version and AFAIR we just wanted to switch to a working version back then. IMO using the latest Java 8 is reasonable.

**Review by kiview — APPROVED** [review]

**Comment by rnorth** [comment]
I don't recall the specific trigger to pin the version exactly, but it's likely a general habit of wanting to pin for reproduceability. In the light of issues like https://github.com/mirromutth/r2dbc-mysql/issues/182, I think this pinning is actually valuable. Could we perhaps reinstate the precise latest version of Temurin 1.8?

**Comment by pioorg** [comment]
Version is pinned now.

**Review by kiview — APPROVED** [review]
LGTM

**Review by rnorth — APPROVED** [review]

**Pull request merged**
