### PR TITLE
Refs #127: Upgrade dduportal/docker-compose container image to 1.6.0

### PR DESCRIPTION
**Pull request by rnorth**

### CODE REVIEW

**Comment by rnorth** [comment]
Oh oh - failures on Travis CI (and I think Circle CI as well):
```
09:00:32.365 [main] INFO  🐳 [dduportal/docker-compose:1.6.0] - Docker compose container is running - service creation will start now
09:00:32.598 [pool-15-thread-1] INFO  🐳 [dduportal/docker-compose:1.6.0] - STDERR: client is newer than server (client API version: 1.21, server API version: 1.20)
09:00:32.650 [pool-15-thread-1] INFO  🐳 [dduportal/docker-compose:1.6.0] - END: null
```

**Comment by rnorth** [comment]
Looks like this may be a way to upgrade Docker daemon for Circle CI: https://github.com/dduportal-dockerfiles/docker-compose/blob/master/circle.yml

**Comment by bsideup** [comment]
@rnorth btw, I do love CircleCI, it's great and remains my favourite OSS CD service, but on TC it cases more issues then help IMO. They ship their own fork of Docker, use LXC driver (no `docker exec` :( ), and it's pretty unsteable. Maybe now is the time to disable it? Travis is doing well so far. What do you think?

**Comment by bsideup** [comment]
@rnorth FYI for Compose file format v2 Docker 1.10+ is required

**Comment by rnorth** [comment]
@bsideup yes, there have been more than a few annoyances along the way - we could maybe make Travis CI the 'primary' CI that has a badge on the project README, as it tends to reflect the actual stability of the build more faithfully.

The reason for having two CI services, despite being slightly odd, is that I'm keen to ensure the library remains usable - or as usable as possible - by people using both CI services. Keeping both active seems like the best way to keep ourselves honest and avoid a situation where, for example, we release a major new version and all of a sudden people on Circle/Travis lose features they previously had...

**Pull request merged**
