### PR TITLE
Fix DockerImageName secondary constructor

### PR DESCRIPTION
**Pull request by dant3**
It is cutting down last char of registry name. Faced this issue then tried to use it for my needs.
Shouldn't there be some unit-tests for that? If not, perhaps I could add some.

### CODE REVIEW

**Comment by rnorth** [comment]
Ouch, good spot - sorry you were affected by this, and thanks for the PR.

I think you're right that this would benefit from some unit tests. Would you still be OK to add?

**Comment by dant3** [comment]
Sure, if you like this PR as it is, go ahead.

**Comment by bsideup** [comment]
@dant3 do you still want to add the tests? Seems to be the only missing thing before we can merge this PR :)

**Comment by rnorth** [comment]
Replaced by #2022

**Pull request closed without merging**
