### PR TITLE
use collapse-after for dependencies category

### PR DESCRIPTION
**Pull request by jetersen**
bump release-drafter.yml

You can see it in action here: https://github.com/release-drafter/release-drafter/releases/tag/v5.19.0

### CODE REVIEW

**Review by kiview — APPROVED** [review]

**Comment by rnorth** [comment]
Aha, you beat me to it! Thanks so much @jetersen!

**Comment by jetersen** [comment]
@rnorth your welcome

**Review by bsideup — APPROVED** [review]

**Comment by jetersen** [comment]
Checking the last release notes under dependencies https://github.com/testcontainers/testcontainers-java/releases/tag/1.17.0

Seems like someone manually removed the newline inside the details.

I know we tested this on release-drafter and made sure it produced the correct draft: https://github.com/release-drafter/release-drafter/blob/bb54ed7b74715dd4fe3d0a5c76fb1c570f6fc7b6/lib/releases.js#L264-L273

Example:

```md
<details>
<summary>9 changes</summary>

* Bump minimist from 1.2.5 to 1.2.6 (#1116) @dependabot
* Bump lint-staged from 12.3.6 to 12.3.7 (#1104) @dependabot
* Bump eslint-plugin-unicorn from 41.0.0 to 41.0.1 (#1105) @dependabot
* Bump node from `8c62619` to `d1d5dc5` (#1106) @dependabot
* Bump probot from 12.2.1 to 12.2.2 (#1097) @dependabot
* Bump node from 17.6.0-alpine to 17.7.1-alpine (#1100) @dependabot
* Bump eslint from 8.10.0 to 8.11.0 (#1099) @dependabot
* Bump prettier from 2.5.1 to 2.6.0 (#1102) @dependabot
* Bump lint-staged from 12.3.5 to 12.3.6 (#1103) @dependabot
</details>
```

**Comment by jetersen** [comment]
Good thing that feature is requested for release drafter 😅

**Comment by kiview** [comment]
We have a very specific process to merge dependabot PRs:
https://www.testcontainers.org/contributing/#combining-dependabot-prs

This means, we have to manually inline the actual dependabot PRs that were included in the combined PR. It's probably too specific to us for release-draft to take care of it 🙂

**Comment by jetersen** [comment]
@kiview make an easy workaround we could add inside release drafter was a HTML comment to help you insert correctly into the details block? 😉

**Comment by kiview** [comment]
Oh yes, I would love this @jetersen 😍

**Pull request merged**
