### PR TITLE
Allow for docker timestamps with timezone offsets

### PR DESCRIPTION
**Pull request by candrews**
Docker prefers to use UTC time when making images/containers, but it's happy to parse non-UTC times too. It will then pass those on in its output.

I originally discovered this issue while testing with podman, but it also applies to Docker. For example, from https://github.com/containers/podman/issues/10267#issuecomment-836576979 :
> Docker _prefers_ to use UTC time when making images/containers, but it's happy to parse non-UTC times too. It will then pass those on in its output. For example:
> 
> ```
> C:\Users\***>docker images
> REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
> mcr.microsoft.com/windows/nanoserver   10.0.14393.1066     a943c29f0046        4 years ago         1.01GB
> 
> C:\Users\***>docker image inspect a943c29f0046
> [
>     {
>         "Id": "sha256:a943c29f0046aa2764d32bf9dfeca1d816865729e3fa26be0259915bf78ac05e",
>         "RepoTags": [
>             "mcr.microsoft.com/windows/nanoserver:10.0.14393.1066"
>         ],
>         "RepoDigests": [
>             "mcr.microsoft.com/windows/nanoserver@sha256:ded482e81f381c94458a1d12d995506ac331d6d3180ed6da24ba809b0849a46c"
>         ],
>         "Parent": "",
>         "Comment": "",
>         "Created": "2017-04-11T02:12:36.3606843-07:00",
>         [...]
> ```

### CODE REVIEW

**Comment by candrews** [comment]
> Could you please add a (parameterized?) test to make sure that we won't introduce a regression in the future?

I don't think a parameterized test is necessary. `DateTimeFormatter.ISO_OFFSET_DATE_TIME` accepts everything `DateTimeFormatter.ISO_INSTANT` accepts and more, so replacing `ISO_INSTANT` with `ISO_OFFSET_DATE_TIME` in the existing test should prevent any future regressions.

**Comment by matejvasek** [comment]
@candrews 
sample solotion:
```diff
diff --git a/core/src/test/java/org/testcontainers/utility/DockerStatusTest.java b/core/src/test/java/org/testcontainers/utility/DockerStatusTest.java
index 4b63719f..be836606 100644
--- a/core/src/test/java/org/testcontainers/utility/DockerStatusTest.java
+++ b/core/src/test/java/org/testcontainers/utility/DockerStatusTest.java
@@ -2,11 +2,16 @@ package org.testcontainers.utility;
 
 import com.github.dockerjava.api.command.InspectContainerResponse;
 import org.junit.Test;
+import org.junit.runner.RunWith;
+import org.junit.runners.Parameterized;
 import org.mockito.Mockito;
 
 import java.time.Duration;
 import java.time.Instant;
+import java.time.ZoneOffset;
 import java.time.format.DateTimeFormatter;
+import java.util.TimeZone;
+import java.util.function.Function;
 
 import static org.junit.Assert.assertFalse;
 import static org.junit.Assert.assertTrue;
@@ -15,33 +20,53 @@ import static org.mockito.Mockito.when;
 /**
  *
  */
+@RunWith(Parameterized.class)
 public class DockerStatusTest {
 
     private static Instant now = Instant.now();
 
-    private static InspectContainerResponse.ContainerState running =
-        buildState(true, false, buildTimestamp(now.minusMillis(30)), DockerStatus.DOCKER_TIMESTAMP_ZERO);
-
-    private static InspectContainerResponse.ContainerState runningVariant =
-        buildState(true, false, buildTimestamp(now.minusMillis(30)), "");
-
-    private static InspectContainerResponse.ContainerState shortRunning =
-        buildState(true, false, buildTimestamp(now.minusMillis(10)), DockerStatus.DOCKER_TIMESTAMP_ZERO);
-
-    private static InspectContainerResponse.ContainerState created =
-        buildState(false, false, DockerStatus.DOCKER_TIMESTAMP_ZERO, DockerStatus.DOCKER_TIMESTAMP_ZERO);
-
-    // a container in the "created" state is not running, and has both startedAt and finishedAt empty.
-    private static InspectContainerResponse.ContainerState createdVariant =
-        buildState(false, false, null, null);
-
-    private static InspectContainerResponse.ContainerState exited =
-        buildState(false, false, buildTimestamp(now.minusMillis(100)), buildTimestamp(now.minusMillis(90)));
+    private static Duration minimumDuration = Duration.ofMillis(20);
 
-    private static InspectContainerResponse.ContainerState paused =
-        buildState(false, true, buildTimestamp(now.minusMillis(100)), DockerStatus.DOCKER_TIMESTAMP_ZERO);
+    @Parameterized.Parameter(0)
+    public InspectContainerResponse.ContainerState running;
+    @Parameterized.Parameter(1)
+    public InspectContainerResponse.ContainerState runningVariant;
+    @Parameterized.Parameter(2)
+    public InspectContainerResponse.ContainerState shortRunning;
+    @Parameterized.Parameter(3)
+    public InspectContainerResponse.ContainerState created;
+    @Parameterized.Parameter(4)
+    public InspectContainerResponse.ContainerState createdVariant;
+    @Parameterized.Parameter(5)
+    public InspectContainerResponse.ContainerState exited;
+    @Parameterized.Parameter(6)
+    public InspectContainerResponse.ContainerState paused;
+    @Parameterized.Parameter(7)
+    public String name;
+
+
+    private static Object[] createTestData(Function<Instant,String> formatter, String name) {
+        return new Object[] {
+            buildState(true, false, formatter.apply(now.minusMillis(30)), DockerStatus.DOCKER_TIMESTAMP_ZERO),
+            buildState(true, false, formatter.apply(now.minusMillis(30)), ""),
+            buildState(true, false, formatter.apply(now.minusMillis(10)), DockerStatus.DOCKER_TIMESTAMP_ZERO),
+            buildState(false, false, DockerStatus.DOCKER_TIMESTAMP_ZERO, DockerStatus.DOCKER_TIMESTAMP_ZERO),
+            // a container in the "created" state is not running, and has both startedAt and finishedAt empty.
+            buildState(false, false, null, null),
+            buildState(false, false, formatter.apply(now.minusMillis(100)), formatter.apply(now.minusMillis(90))),
+            buildState(false, true, formatter.apply(now.minusMillis(100)), DockerStatus.DOCKER_TIMESTAMP_ZERO),
+            name
+        };
+    }
 
-    private static Duration minimumDuration = Duration.ofMillis(20);
+    @Parameterized.Parameters(name = "{7}")
+    public static Object[][] data() {
+        return new Object[][] {
+            createTestData(DateTimeFormatter.ISO_INSTANT::format, "with UTC"),
+            createTestData(inst -> inst.atOffset(ZoneOffset.ofHours(1)).format(DateTimeFormatter.ISO_OFFSET_DATE_TIME), "with positive offset"),
+            createTestData(inst -> inst.atOffset(ZoneOffset.ofHoursMinutes(-1, -30)).format(DateTimeFormatter.ISO_OFFSET_DATE_TIME), "with negative offset"),
+        };
+    }
 
     @Test
     public void testRunning() throws Exception {
@@ -66,7 +91,7 @@ public class DockerStatusTest {
     }
 
     private static String buildTimestamp(Instant instant) {
-        return DateTimeFormatter.ISO_INSTANT.format(instant);
+        return DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(instant);
     }
 
     // ContainerState is a non-static inner class, with private member variables, in a different package.
```

**Comment by candrews** [comment]
Is this PR now mergeable?
If not, please let me know what I can do.

Thank you!

**Comment by bsideup** [comment]
Hi @candrews,

Could you please rework the tests, so that there is only one `ContainerState` parameter? That's how usually parameterized tests are used. Thanks!

**Comment by candrews** [comment]
> Hi @candrews,
> 
> Could you please rework the tests, so that there is only one `ContainerState` parameter? That's how usually parameterized tests are used. Thanks!

I adjusted it so there aren't any `ContainerState` parameters - the `DateTimeFormatter` is now the parameter. I think that makes the test more readable and is more like the original test.

**Comment by candrews** [comment]
I believe that I've addressed the feedback received so far. Can this please be reviewed again and (potentially) merged?

**Review by rnorth — APPROVED** [review]
This looks fine to me, thanks @candrews and sorry this has taken a long time to review.

FWIW, I think there's something quite interesting here: I was unable to replicate the original problem locally (and [this glot.io snippet](https://glot.io/snippets/g0ippb9jqq) illustrates this, I think). This seems bizarre, so I did a bit of digging. Apparently this problem was actually considered a [bug in the JDK](https://bugs.openjdk.java.net/browse/JDK-8166138) which was fixed in https://github.com/openjdk/jdk/commit/f5d19b9109c7a0a40a85ca022d3089230ed1456b (which seems to have made it into JDK12+).

Perhaps this explains why we've not heard about this problem more often.

But regardless, we're not about to drop support for older JDKs, so I'm very happy to accept this PR.

**Pull request merged**
