### PR TITLE
Exclude id from NetworkImpl.NetworkImplBuilder (testcontainers#8125)

### PR DESCRIPTION
**Pull request by quincy**
This seemed like an easy issue to get started contributing.  I'm a big fan of the project and have been evangelizing it at my company.

### CODE REVIEW

**Comment by rnorth** [comment]
We had some issues with the quay.io docker registry, which caused the build to fail. Will update the branch from master to include #2805.

**Comment by quincy** [comment]
Thanks @rnorth, I saw quay was having problems again.

**Comment by rnorth** [comment]
Looks like we have a check failure in the `:testcontainers:japicmp` task 🤔 
We may have a binary backwards compatibility problem to think about here...

**Comment by bsideup** [comment]
@rnorth we definitely do, because the constructor was public :) Let's make it backward compatible and deprecate first

**Comment by quincy** [comment]
Assuming you want something like this?
```
@Deprecated
public NetworkImpl() {}
```

**Comment by bsideup** [comment]
@quincy no, the other one ("all args constructor"), with the `id`

**Comment by quincy** [comment]
Ah, right, because `@Builder` would need to create an all-args constructor in order for it to do its job.

**Comment by quincy** [comment]
That doesn't appear to have fixed the issue.  It's still complaining about the removed setter.

**Comment by quincy** [comment]
Okay, I've pushed a new commit which delomboks the existing builder, and deprecates the `id` method directly.  After this has been released we can go back in and remove the deprecated stuff and throw the `@Builder` annotation back on.

If you guys know a better way to deal with this through lombok directly, please clue me in.  I did not find anything in their documentation which looked promising.

**Comment by bsideup** [comment]
@quincy I wonder if adding `@Deprecated` on a field makes it deprecated in the builder, too. Could you please check?

**Comment by quincy** [comment]
@bsideup, yes, marking the field deprecated makes it deprecated in the builder.  I believe you are suggesting we could mark the `id` field deprecated for now and release.  Then after the release we can come back and implement my original change to have the builder without the `id`, and at that point we could remove the deprecated annotation from `id`.

Let me know if that sounds good, or if you have something else in mind, and I can get that change pushed.

**Comment by bsideup** [comment]
@quincy yes, this definitely sounds good 👍

**Comment by quincy** [comment]
@bsideup, @rnorth,

Was there anything else you guys wanted me to do on this branch at the moment?

**Comment by bsideup** [comment]
@quincy thanks for the ping. I guess we should also override `getId` and **not** mark it as deprecated, because the getter is definitely not :)

**Comment by quincy** [comment]
@bsideup, the getter is already overridden.
```
        @Override
        public synchronized String getId() {
            if (initialized.compareAndSet(false, true)) {
                id = create();
            }

            return id;
        }
```

I am not really familiar with lombok so I am not sure how to solve that.  Any suggestions?

**Comment by quincy** [comment]
I got quite a bit more busy so I kind of lost track of this, but I'm still interested in finishing this PR.  I'm not sure what the best way forward is though, are there any suggestions about how to deal with the getter being marked deprecated?

**Comment by rnorth** [comment]
I think the PR is having the desired effect:
image

I'm going to approve but not merge; @bsideup if you think this is missing something still please say.

**Review by rnorth — APPROVED** [review]

**Comment by bsideup** [comment]
@quincy @rnorth looks good! 💯

**Comment by quincy** [comment]
Thanks @bsideup , @rnorth !

**Pull request merged**
