### PR TITLE
Add retry logic around checkExposedPort pre-flight check 

### LINKED ISSUE #513: Unnable to start container - checkExposedPort - NullPointerException
Hi,

this is not very common issue (sometime happens, but not very often). Testcontainers java client is failing due NullPointerException while container initialization in checkExposedPort method. See error below:

```

java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.junit.runners.model.FrameworkField.get(FrameworkField.java:73)
	at org.junit.runners.model.TestClass.getAnnotatedFieldValues(TestClass.java:230)
	at org.junit.runners.ParentRunner.classRules(ParentRunner.java:255)
	at org.junit.runners.ParentRunner.withClassRules(ParentRunner.java:244)
	at org.junit.runners.ParentRunner.classBlock(ParentRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:362)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
	at org.testcontainers.DockerClientFactory.checkExposedPort(DockerClientFactory.java:186)
	at org.testcontainers.DockerClientFactory.lambda$client$1(DockerClientFactory.java:129)
	at org.testcontainers.DockerClientFactory.runInsideDocker(DockerClientFactory.java:230)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:118)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:116)
	at org.testcontainers.containers.FixedHostPortGenericContainer.<init>(FixedHostPortGenericContainer.java:16)
	at Test.<clinit>(Test.java:62)
	... 26 more


```

### PR DESCRIPTION
**Pull request by rnorth**
… for improved robustness (fixes #513).

### CODE REVIEW

**Comment by rnorth** [comment]
#513 sounds like a challenging one to reproduce - it's not something I've seen before. Based on the code, a Null Pointer Exception should not be raised if things are working. It must only happen if the exposed port check is already on the way to failing. Because it's an intermittent issue, it seems there might be a timing issue.

With this PR I've added a simple, 3 second, retry loop around the port check logic. It's hard to know if this will help, but it's probably the most we can do to try and resolve without a way to reproduce.

**Comment by VladoDemcak** [comment]
thanks for fix @rnorth. I see this change in [CHANGELOG.md](https://github.com/testcontainers/testcontainers-java/blob/1.5.0/CHANGELOG.md)as implemented in `1.5.0` but we are using latest `1.5.0` from maven central repository and  It's not here. Also I see this PR as open.

**Comment by rnorth** [comment]
Damn, sorry - not sure what happened here, but undoubtedly my fault. Will release with this included ASAP.

**Comment by VladoDemcak** [comment]
thanks everybody for fixing. @rnorth when do we expect to release new version?

**Pull request merged**
