### PR TITLE
Allow mysql customizations

### PR DESCRIPTION
**Pull request by nickbabcock**
This is #220 but for maria and mysql

### CODE REVIEW

**Comment by bsideup** [comment]
Hi @nickbabcock,

We just moved MariaDB to a separate repo: 
https://github.com/testcontainers/testcontainers-java-module-mariadb

Any chance you can submit it there? :) Sorry about that :)

**Comment by nickbabcock** [comment]
Ok removed all mention and code related to mariadb from this PR.

**Comment by bsideup** [comment]
@nickbabcock I just think what if we move this to JDBCContainer so that every JDBC-based implementation will receive this functionality?

**Comment by nickbabcock** [comment]
Are you talking about adding abstract `with` methods to `JdbcDatabaseContainer`? Outside of them being environment variables, I can't see a a common way for setting these parameters across db containers.

**Comment by kiview** [comment]
I prefer @bsideup's idea as well, using an abstract `with` method as you proposed. For those database who don't yet have this functionality and for which you don't know how to implement it right now, we could throw a `UnsupportedOperationException` and create an issue to support this in the future.

**Pull request closed without merging**
