### PR TITLE
environmentSupportsReuse() uses classpath properties

### PR DESCRIPTION
**Pull request by gusega**
environmentSupportsReuse() uses classpath properties

### CODE REVIEW

**Comment by eddumelendez** [comment]
Hi @gusega, before submitting a PR please discuss with the team about changes. We really appreciate your contribution and your time. However, regarding this change, reuse is still an experimental feature. The side effect about having it enabled by default is users not realizing the containers with reuse mode enabled will be running in the background.

**Comment by gusega** [comment]
@eddumelendez this is not about enabling it by default its about picking it up from properties file.
The comment above
```
// specifically not supported as an environment variable or classpath property
```
Is misleading. It is supported as environment variable.

**Comment by eddumelendez** [comment]
> this is not about enabling it by default its about picking it up from properties file.

I got it and that's what we try to avoid.

> The comment above
// specifically not supported as an environment variable or classpath property
Is misleading. It is supported as environment variable.

Let's fix the comment, then.

**Comment by gusega** [comment]
@eddumelendez i dont get it why is ok to have it in environment variable or home properties, but not ok in properties file?

**Comment by eddumelendez** [comment]
> The side effect about having it enabled by default is users not realizing the containers with reuse mode enabled will be running in the background.

I meant the intention to support it in `testcontainers.properties` in your project and enabling the feature will cause what I described if the file is committed in the project repository. We know enabling reuse it's an extra step but due to the side effects, users should be aware about the feature is being enabled and that's why they should do it.

**Comment by gusega** [comment]
@eddumelendez  now I understand thanks.

By the way, I think TC_REUSE should just keep the container. If I want to keep the container running, I use TC_DEAMON.

**Pull request closed without merging**
