### PR TITLE
2472: Add support for container_name in docker-compose file

### PR DESCRIPTION
**Pull request by reggiemcdonald**
Closes: #2472 

This PR adds support for `container_name` in the docker-compose file by pulling the container names out in `ParsedDockerComposeFile` and adding some additional logic in `DockerComposeContainer`

This is my first time contributing to the repo, so any feedback is welcomed.

### CODE REVIEW

**Comment by reggiemcdonald** [comment]
I'm not really sure about this failing CI. Any suggestions? I just wanted to rebase this branch with master

**Comment by bsideup** [comment]
@reggiemcdonald I just triggered a re-run, there was some issue with downloading Gradle stuff

**Comment by reggiemcdonald** [comment]
@bsideup thanks!

**Comment by wnyffenegger** [comment]
@rnorth @bsideup @kiview having this feature is a blocking issue for me is there a plan to merge this change in?

**Comment by raztiff** [comment]
Thanks @reggiemcdonald great work

Is this still looking to be merged in? Currently the latest version (as of writing this) is `1.15.2` and this issue is still casuing problems.

**Comment by jeremyjams** [comment]
Hi @reggiemcdonald, thank you! Do you have any plan on merging it @rnorth?

**Comment by kadaan** [comment]
@reggiemcdonald Can this get merged?

**Comment by eitzenbe** [comment]
Any update on landing this?

**Comment by cunhap** [comment]
@rnorth @bsideup @kiview Can this PR be merged, please?

**Comment by svalexxx** [comment]
Is there any news about this PR?

**Comment by swanysimon** [comment]
@bsideup or @reggiemcdonald , what's the status here? If you don't have time or energy here, I'm happy to take over the PR

**Comment by jghoman** [comment]
Would also love to see this merged, and can take it over if someone needs to.  Status?

**Comment by kiview** [comment]
Thanks for the PR @reggiemcdonald, but unfortunately we have to close it. Mainly, there are 2 reasons why we don't want to add support for `container_name` to `DockerComposeContainer`:

1. It requires us to further parse the Docker Compose file and its format has been slightly volatile in the past. So we generally want to avoid further semantically parsing the Docker Compose file, independent from the actual `container_name` key.
2. Using `container_name` would break existing `DockerComposeContainer` features, like scaling.
3. As the Testcontainers library, we want to avoid the usage of _fixed_ things, such as ports, names, etc., since those introduce the anti-pattern of _integrated tests_ that can fail depending on the state of the environment in which they are running.

**Comment by orpheusx** [comment]
@kiview The reasons for closing this seem fairly arbitrary from my point of view. Responding to your numbered reasons in order:
1. Format volatility ebbs and flows over time but if the project wants to support compose files at all it seems better to at least not actively get in the way (by throwing exception over valid syntax.) My sense is that V2 has been more stable. (Note: the issue with container_name applies to the newer ComposeContainer as well as the now deprecated DockerComposeContainer.)
2. Not sure how this would break scaling. An issue with Testcontainers Cloud?
3. I agree that users should avoid environment state dependencies but providing supporting docker-compose files _at all_ seems to be a pragmatic choice that recognizes the need that have been expressed above and in the original ticket, https://github.com/testcontainers/testcontainers-java/issues/2472.

For what it's worth, I just ran into this issue and would really like to see a solution because, in most other ways, Testcontainers is awesome.

**Pull request closed without merging**
