### PR TITLE
Upgrade cassandra driver 4.10.0

### PR DESCRIPTION
**Pull request by vroyer**
### Motivations

Unit tests with the OSS Cassandra driver version 4.10.0

### Modifications

* Upgrade the Cassandra driver.

### Tests

Exclude the fasterxml (core+databind) from the cassandra driver deps to avoid an issue with docker-java. All unit tests are ok.

### CODE REVIEW

**Comment by nikeee** [comment]
Any chance to get this merged?

**Comment by alexherr** [comment]
Is it planned to support Cassandra 4?

**Comment by eddumelendez** [comment]
Cassandra 4.x is already supported, see [this test](https://github.com/testcontainers/testcontainers-java/blob/6a3e649b296bba3c5723a2538b21d4eabb593cae/modules/cassandra/src/test/java/org/testcontainers/containers/CassandraDriver4Test.java#L15-L14). However, there is a limitation when is used with `withInitScript()`. Our recommendation is to use something like [liquibase-cassandra](https://github.com/liquibase/liquibase-cassandra)

**Comment by vroyer** [comment]
The issue is not related to Cassandra 4.x, but about the cassandra **driver** 4.10+

**Comment by eddumelendez** [comment]
A new implementation has been added in #8616 and it doesn't rely on the cassandra client.

**Pull request closed without merging**
