### PR TITLE
Support timestamps with offset from "inspect image"

### LINKED ISSUE #3054: DateTimeParseException when trying to launch container
When Testcontainers is refreshing its local image cache, it is using the command "inspect image" and parses the timestamp of the attribute "created". If this timestamp contains a time zone offset, then the following exception is thrown and Testcontainers fails to launch the container.
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=docker-registry.example.org/some/image:1.0, imagePullPolicy=DefaultPullPolicy())
Caused by: java.time.format.DateTimeParseException: Text '2020-07-24T07:17:51.365190246+02:00' could not be parsed at index 29
```
This happend with Docker version 18.06.3 on Linux.

### PR DESCRIPTION
**Pull request by acanda**
The command "inspect image" can return a "created" timestamp without a
time zone offset (e.g. "2020-07-27T18:23:31.365190246Z") or with a time
zone offset (e.g. "2020-07-27T18:23:31.365190246+02:00"). This change
adds support for timestamps with a time zone offset.

This fixes #3054.

### CODE REVIEW

**Comment by jokogr** [comment]
Is there any way to use this already? E.g., publish it on a private Artifactory?

**Comment by aoksenholt** [comment]
Will this PR be included in a future release?

**Comment by eivinwi** [comment]
This is currently a blocking issue for us. Would be great to get this resolved

**Review by bsideup — APPROVED** [review]

**Comment by bsideup** [comment]
@acanda merged, thanks! Sorry it took so long :)

**Pull request merged**
